### ISSUE TITLE
Misaligned modifier formatting with low print width

### ISSUE THREAD

**Issue by abandeali1** [prettier-solidity/prettier-plugin-solidity#105]
There is some misalignment when the `printWidth` is shorter than a single modifier line. See this example: https://github.com/0xProject/0x-monorepo/compare/feat/contracts/prettier#diff-1b7ac3458f8bab7e6b28979b9e83204eR45

**Comment by abandeali1** [comment]
Looking through the rest of the changes in that same link, there are some other spots where formatting seems off:

https://github.com/0xProject/0x-monorepo/compare/feat/contracts/prettier#diff-f5fdf140da4853d6853328e22e0b49faR194

https://github.com/0xProject/0x-monorepo/compare/feat/contracts/prettier#diff-413d1eb3360a1c7d7357ce886080d9d2R143

**Comment by mattiaerre** [comment]
I've added a branch w/ one of the examples you mentioned above @abandeali1 

https://github.com/prettier-solidity/prettier-plugin-solidity/blob/MixinMatchOrders/tests/MixinMatchOrders/__snapshots__/jsfmt.spec.js.snap

**Comment by abandeali1** [comment]
Hmm I'm still seeing all of the same misalignments (updated from `1.0.0-alpha.16` to `1.0.0-alpha.17`). What are the `.prettierrc` configs in the snapshot?

**Comment by mattiaerre** [comment]
the latest version is the https://github.com/prettier-solidity/prettier-plugin-solidity/releases/tag/v1.0.0-alpha.18 not sure what you mean about the `.prettierrc` configs in the snapshot; but globally we have these ones https://github.com/prettier-solidity/prettier-plugin-solidity/blob/master/.prettierrc

**Comment by fvictorio** [comment]
> What are the `.prettierrc` configs in the snapshot?

I think it just uses the default values.

**Comment by fvictorio** [comment]
Thanks a lot for the feedback, @abandeali1. I created issues #115, #116 and #117. If you think those three cover everything you said here, we can close this issue.

**Comment by mattiaerre** [comment]
is this issue covered by #115 #116 and #117 ?
I'd love to close this one if that's the case @abandeali1 
// cc @fvictorio

**Comment by fvictorio** [comment]
I think we can close this.
