### ISSUE TITLE
Base contracts don't respect print width

### ISSUE THREAD

**Issue by fvictorio** [prettier-solidity/prettier-plugin-solidity#113]
As discussed in https://github.com/0xProject/0x-monorepo/pull/1495, if a contract has a lot of base contracts, these should be split to respect the print width.

```solidity
contract Foo is AContract, AnotherContract, YetAnotherContract, ThisShouldBeSplit {
  function foo(uint x, uint x2, uint x3, uint x4, uint x5, uint x6, uint x7, uint x8) {
    a = 1;
  }
}
```

This should split the base contracts, but just the function parameters are split.

**Comment by mattiaerre** [comment]
closing it thanks to #134

**Comment by mattiaerre** [comment]
closing it thanks to #134
