### ISSUE TITLE
.eslintrc

### ISSUE THREAD

**Issue by mattiaerre** [prettier-solidity/prettier-plugin-solidity#130]
# Description

- add `implicit-arrow-linebreak`

**Comment by fvictorio** [comment]
This seems like the kind of eslint rule that you can't use along with prettier (core prettier I mean, the one used here for formatting javascript). In fact, [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier/blob/d3a0c0d80ca04ab3f1d106481ea2c3bb39abc04f/index.js#L36) disables it. We aren't using that config right now, but it's very common to include it when using prettier.

**Comment by minggas** [comment]
Hi, can I give a try?

**Comment by fvictorio** [comment]
Hi @minggas! I don't know if we are going to do this, but maybe you want to give https://github.com/prettier-solidity/prettier-plugin-solidity/issues/140 a try? If you need some pointers, we'd be happy to help you.

**Comment by mattiaerre** [comment]
Hi @fvictorio you are right, we are `"extends": "airbnb"` and not using `eslint-config-prettier`; shall we rename this issue in use `eslint-config-prettier` instead? in that case woul @minggas give it a try?

**Comment by fvictorio** [comment]
That sounds like a good idea, yes.

**Comment by minggas** [comment]
I like to give a try if it's ok with you.

The change will be on the .eslintrc:
from:
```
"rules": {
    "arrow-parens": "off",
    "comma-dangle": "off",
    "object-curly-newline": "off"
  }
```
to:
```
"rules": {
    "arrow-parens": "off",
    "comma-dangle": "off",
    "object-curly-newline": "off",
    "eslint-config-prettier": "off"
  }
```
am i right?

**Comment by fvictorio** [comment]
No, that won't work. `eslint-config-prettier` is a config, not a rule. Check the "Installation" section in https://github.com/prettier/eslint-config-prettier docs.

**Comment by mattiaerre** [comment]
I'm gonna close this as #149 has been merged, thanks @minggas
