### ISSUE TITLE
Should single line trueBody and falseBody be indented in a new line?

### ISSUE THREAD

**Issue by Janther** [prettier-solidity/prettier-plugin-solidity#137]
In the [Style Guide](https://solidity.readthedocs.io/en/v0.5.9/style-guide.html#control-structures) every time there is a single line body for an if or an else, it is printed in a new line.

This is not a rule described in the document. However, I'd rather have this:

```Solidity
if (x < 10)
    x += 1;

if (x < 3)
    x += 1;
else
    x -= 1;
```
than this:
```Solidity
if (x < 10) x += 1;

if (x < 3) x += 1;
else x -= 1;
```

Open to comments. @fvictorio @mattiaerre

**Comment by fvictorio** [comment]
I also prefer the first snippet. On the other hand, the second snippet is more consistent with how Prettier formats javascript. This doesn't mean that we necessarily have to do it that way, but it's a good heuristic for making decisions.

(While we're on it, I'm also in the "always use braces in conditionals" team, but that's a different discussion, and I'm probably on the losing side :smile:)

**Comment by mattiaerre** [comment]
I agree w/ @fvictorio that we should follow what prettier for JavaScript does as a rule of thumb, but I'm confused now: shall we go w/ one or two? 🤔

**Comment by fvictorio** [comment]
I vote for following the style guide here.

**Comment by fvictorio** [comment]
Actually, it would be good to check some codebases (zeppelin, 0x, gnosis multisig) and see what they do.

**Comment by Janther** [comment]
closing since the last developments in the indentation on `if`, `while`, and `for` statements show a lot of improvement in this case.
