### ISSUE TITLE
Force braquets when if statement is longer than a line

### ISSUE THREAD

**Issue by Janther** [prettier-solidity/prettier-plugin-solidity#138]
According to the [Style Guide](https://solidity.readthedocs.io/en/v0.5.9/style-guide.html#control-structures) if we have more than a line in a `trueBody` or a `falseBody`, we should enforce braquets.

Before Prettier.
```Solidity
if (x < 10)
    someArray.push(Coin({
        name: 'spam',
        value: 42
    }));
```
After Prettier.
```Solidity
if (x < 10) {
    someArray.push(Coin({
        name: 'spam',
        value: 42
    }));
}
```

**Comment by fvictorio** [comment]
This seems like a non-trivial implementation, but I think it can be done. Maybe it makes sense to fix this and #137 (if it's accepted) together.

**Comment by Janther** [comment]
Theoretically this can be done using the [ifBreak](https://github.com/prettier/prettier/blob/master/commands.md#ifbreak) builder.
```Javascript
concat([ifBreak('{', ''), trueBody, ifBreak('}', '')])
```
I'll have to test it though.

**Comment by Janther** [comment]
ok, I did this one and I found a problem.

If I take this:
```Solidity
if (true) return true;
```

the AST for the trueBody is:
```JSON
"trueBody": {
    "expression": {
      "type": "BooleanLiteral",
      "value": true,
    },
    "type": "ReturnStatement",
  }
}
```

If I take this:
```Solidity
if (true) { return true; }
```

the AST for the trueBody is:
```JSON
"trueBody": {
  "statements": [
    {
      "expression": {
        "type": "BooleanLiteral",
        "value": true,
      },
      "type": "ReturnStatement",
    },
  ],
  "type": "Block",
}
```

Modifying the AST compare test for this use case is something we need to discuss.

This would benefit `if`, `while`, and `for` statements.
The changes are in this [branch](https://github.com/prettier-solidity/prettier-plugin-solidity/tree/feature/add_brackets_if_while_for_body_when_splits)

Please have a look.
@mattiaerre @fvictorio

**Comment by Janther** [comment]
also, this introduces a small regression for the particular case if a single line `trueBody` followed by an `else`.
```Solidity
if (ifCondition) return true;
else return false;

if (ifCondition) return true;
else if (elseIfCondition) return (true, false);
else return false;
```

will be prettified as
```Solidity
if (ifCondition) {
    return true;
} else return false;

if (ifCondition) {
    return true;
} else if (elseIfCondition) {
    return (true, false);
} else return false;
```
this is due to a hardline needed in the `ifBreak`'s `noBreak` parameter when there's an else which forces a break if there are no breaks 😅.

**Comment by Janther** [comment]
bonus feature:
guess what this should be prettified into:
```Solidity
if (simpleIf) if (simpleIfWithinIf) return true; else return false;
```
Spoiler Alert
```Solidity
if (simpleIf) {
    if (simpleIfWithinIf) {
        return true;
    } else return false;
}
```
