### ISSUE TITLE
modifiers should always split if arguments split

### ISSUE THREAD

**Issue by Janther** [prettier-solidity/prettier-plugin-solidity#139]
According to the [Style Guide](https://solidity.readthedocs.io/en/v0.5.9/style-guide.html#function-declaration) if the parameters of a function break, so do the modifiers. If the modifiers break, the parameters not necessarily do.

```Solidity
function thisFunctionHasLotsOfArguments(
    address a,
    address b,
    address c,
    address d,
    address e,
    address f
)
    public
{
    doSomething();
}

function thisFunctionNameIsReallyLong(address x, address y, address z)
    public
    onlyowner
    priced
    returns (address)
{
    doSomething();
}
```

This seems like a nitpick but I'm putting it here so we can address it in the future. @fvictorio @mattiaerre

**Comment by fvictorio** [comment]
There was some discussion somewhere (can't find it right now) about the position of the opening brace. This seems to suggest that the opening brace goes in its own line if the modifiers were split, but in the same line of the function if there's no splitting.

Personally, I like that approach, and I don't mind the inconsistency.

**Comment by fvictorio** [comment]
Closing this in favor of #474.
