### ISSUE TITLE
whitespace around and operator can be omitted

### ISSUE THREAD

**Issue by Janther** [prettier-solidity/prettier-plugin-solidity#142]
In the other recommendations section fo the [Style Guide](https://solidity.readthedocs.io/en/v0.5.9/style-guide.html#other-recommendations) it is said that an operator is allowed to have no whitespace around it in order to express the priority of execution.

```Solidity
x = 2**3 + 5;
x = 2*y + 3*z;
x = (a+b) * (a-b);
```

I'm not that fond of this one.
Comments? @fvictorio @mattiaerre

**Comment by fvictorio** [comment]
Yeah, I don't love this idea. I think at some point I considered removing the spaces just for the `**` operator, but I ended up not doing it because js prettier also adds them.
