### ISSUE TITLE
prettier-solidity logo

### ISSUE THREAD

**Issue by Janther** [prettier-solidity/prettier-plugin-solidity#150]
- [prettier logo](https://raw.githubusercontent.com/prettier/prettier-logo/master/images/prettier-banner-light.png)

![prettier logo](https://raw.githubusercontent.com/prettier/prettier-logo/master/images/prettier-banner-light.png)

- [solidity logo](http://solidity.readthedocs.io/en/v0.4.24/_images/logo.svg)

![solidity logo](http://solidity.readthedocs.io/en/v0.4.24/_images/logo.svg)

Proposal
![prettier-solidity](https://user-images.githubusercontent.com/1022054/59317198-f1149b80-8d15-11e9-9b0f-0c5e7d4b8b81.png)
![prettier-solidity black and white](https://user-images.githubusercontent.com/1022054/59317197-f07c0500-8d15-11e9-92c8-b360b43ae00c.png)

**Comment by mattiaerre** [comment]
wow this is lovely! thanks @Janther I like version 1 personally

**Comment by fvictorio** [comment]
This is awesome! I like both of them :smile:

**Comment by Janther** [comment]
The black and white one is to generate a font icon in case you want to create a fancy button to prettify your code

**Comment by fvictorio** [comment]
I used this logo for the gitcoin grant. @mattiaerre it would be nice to update the org logo too.

**Comment by mattiaerre** [comment]
on it @fvictorio

**Comment by fvictorio** [comment]
Closing this since we are already using it in several places :tada:

**Comment by mattiaerre** [comment]
absolutely @fvictorio however I still think we should find a "simpler" version of this concept as it looks a little bit w/ too many "parts" as, for instance, an icon // cc @Janther

**Comment by Janther** [comment]
Got inspired by the logo on https://github.com/prettier/plugin-ruby and came up with this.

![prettier-solidity1](https://user-images.githubusercontent.com/1022054/103964817-3c787f80-51c1-11eb-9ae3-a3d0bf83287b.png)

There's the caveat of not messing around with the shape of the logo so this is another take on that one.

![prettier-solidity2](https://user-images.githubusercontent.com/1022054/103964981-95481800-51c1-11eb-9a49-969e8a79a110.png)

I know we already have one, just wanted to have some fun and hear feedbacks.

**Comment by mattiaerre** [comment]
fantastic work @Janther that's awesome; I personally would like to see something that scales down better. the small pic of the existing logo is very confusing to me and I'm afraid that this new one would have the same problem. would it be possible to try to remove things and make it overall more simple?

**Comment by Janther** [comment]
I'll try something but would be along those lines, I don't want the logo not to represent prettier in a way or another

**Comment by Janther** [comment]
if you have a look at [Responsive Logos](http://www.responsivelogos.co.uk) and play with the size of the screen we could have a cleaner version for smaller purposes

**Comment by fvictorio** [comment]
Should we close this one?
