### ISSUE TITLE
`emit` gets printed on all Solidity versions

### ISSUE THREAD

**Issue by andremedeiros** [prettier-solidity/prettier-plugin-solidity#158]
The `emit` keyword only works on Solidity >= 0.4.21, so printing it to files with earlier versions will break.

**Comment by Janther** [comment]
it is a very blurry line what a formatter and what a linter responsibilities are.
this case is very close to the middle of that line but a little bit more in the linter spectrum.
Now I'm wondering if we should enforce the `emit` keyword in newer pragmas.

**Comment by Janther** [comment]
also currently prettier allows for either way.

https://github.com/prettier-solidity/prettier-plugin-solidity/blob/a532de4e3829430f5cdc55f1080217391870f620/tests/StyleGuide/__snapshots__/jsfmt.spec.js.snap#L588-L616

**Comment by mattiaerre** [comment]
I personally think this is the responsibility of a linter. as long as this plugin is not adding/removing keywords based on the Solidity version, I'm fine w/ that.

**Comment by andremedeiros** [comment]
Hah, I'll get back to you on this one, sorry.

**Comment by andremedeiros** [comment]
I'm closing this on account of being an idiot. Sorry.
