### ISSUE TITLE
Modifier Declarations without parameters should not have parentheses

### ISSUE THREAD

**Issue by Janther** [prettier-solidity/prettier-plugin-solidity#165]
`solidity-parser-antlr`'s new [version](https://github.com/federicobond/solidity-parser-antlr/pull/77) will introduce a breaking change by removing `Parameter` and `ParameterList` and using a collection of `VariableDeclaration` instead.
I made the changes and discovered that we no longer will be able to know when a modifier without parameters has been declared like this:
```Solidity
modifier a {
    _;
}
```
or like this:
```Solidity
modifier a() {
    _;
}
```
for the time being, I asked @federicobond to add the case that if no parentheses where given, the parser could show `null` instead of an empty array `[]`.
He agreed but is a bit reluctant about this change.
This solution was inspired by the use case where constructor modifiers need to preserve parentheses otherwise the code will not compile.

In the constructor modifier, this is necessary until @federicobond finds a better way to describe that a modifier is a constructor call.
In a modifier declaration this solution is not really needed as both declarations (with and without parentheses) generate the same bytecode.

Since prettier is supposed to be an opinionated formatter I propose that the parser should not take care of this use case and prettier-solidity should always print modifier declarations without parentheses.

That way the parser will be closer to an AST rather a Concrete Syntax Tree (which was @federicobond's issue with this change). And we would still offer a propper prettified code.

**Comment by fvictorio** [comment]
This seems to work fine now.
