### ISSUE TITLE
Add instructions on how to configure this with format-on-save

### ISSUE THREAD

**Issue by pcowgill** [prettier-solidity/prettier-plugin-solidity#176]
It would be helpful to add instructions on how to configure this with [format-on-save, for instance in `VS Code`](https://github.com/prettier/prettier-vscode#format-on-save).

Or if that's not possible yet, that would be good to know too.

Thanks!

**Comment by mattiaerre** [comment]
hi @pcowgill it looks like it's not possible to configure VS Code to have format on save using this plugin, some more info from @fvictorio: 

- there is a pending PR that will allow you to add any prettier plugin to prettier-vscode. prettier/prettier-vscode#757

- I just made the PR #166 that will make our plugin compatible with the version of prettier/prettier-vscode#757

I, although, didn't try lately to see if the integration w/ VS Code is actually possible, if you manage to do it please let us know and we'll be more than happy to update our README or, if you don't mind, accept PRs

**Comment by fvictorio** [comment]
It would be nice to have a section on integrations, though. I can write the section for vim. For VS, we can indicate that it's a work on progress, and update it when it's working.

**Comment by mattiaerre** [comment]
that sounds great @fvictorio

**Comment by mattiaerre** [comment]
we've updated our readme @pcowgill is that of any help? can we close this issue?

**Comment by pcowgill** [comment]
@mattiaerre Yep, that's helpful. Thanks! Closing this!
