### ISSUE TITLE
solidity-parser-antlr-v0.5.0

### ISSUE THREAD

**Issue by Janther** [prettier-solidity/prettier-plugin-solidity#181]
the unreleased version of the parser has 2 breaking features.

  1. The removal of `ParameterList` and `Parameter` node types.
  2. The inclusion of natspec comments as part of the nodes they are related to.

I made a [branch](https://github.com/prettier-solidity/prettier-plugin-solidity/tree/solidity-parser-antlr-v0.5.0) that deals with the first change.

However the natspec comments are being printed in the worng place now. My theory is that the `loc` object is now including the natspec and then when deciding wher do we print the comment, instead of prepending it to the function, we are apennding it to the `results` statement or a `modifier` or another node before the `block` node.

This might affect not just functions but anything that includes a natspec (further testing is required).

My idea would be to check what can we to have a look at #172, check what we like and what we can improve so we can merge it, and then create new natspec-related rules to prepend these to the correct node.

**Comment by fvictorio** [comment]
@Janther is this still valid?

**Comment by fvictorio** [comment]
Closing this, please re-open if it's still relevant.
