### ISSUE TITLE
Error in Visual Studio Code: "There is no formatter for 'solidity'-files installed."

### ISSUE THREAD

**Issue by tab00** [prettier-solidity/prettier-plugin-solidity#195]
I ran `npm install --save-dev prettier prettier-plugin-solidity` and installed [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension.

Yet I still get the error message when I try to format a solidity file via `Shift Alt F`, which is the default keyboard shortcut to "Format Document" in Visual Studio Code.

Is there some extra setting that needs to be set in Visual Studio Code?

**Comment by mattiaerre** [comment]
@tab00 I am not too sure if VSCode supports plugins for prettier; you may be able to find more info in this other open issue too: #176 

 // cc @fvictorio @Janther

**Comment by mattiaerre** [comment]
@tab00 we've just merged #200 hopefully that helps; let us know if we can close this issue

**Comment by mattiaerre** [comment]
closing thanks to #200
