### ISSUE TITLE
Doesn't work with yark workspaces anymore

### ISSUE THREAD

**Issue by PaulRBerg** [prettier-solidity/prettier-plugin-solidity#196]
Been using this plugin since version `alpha.27`, but recently it stopped working.

```
[error] No parser could be inferred for file
```

It seems I upgraded to `alpha.31`. This is my [monorepo](https://github.com/sablierhq/sablier).

**Comment by mattiaerre** [comment]
thanks for filing this issue @PaulRBerg we'll look into this

 // cc @fvictorio @Janther

**Comment by mattiaerre** [comment]
is this still an issue even w/ the latest version of the plugin @PaulRBerg ?

**Comment by PaulRBerg** [comment]
No, just did a test now. Seems functional!

**Comment by PaulRBerg** [comment]
It looks like this issue returned in prettier-plugin-solidity@1.0.0-alpha.58.

Related: https://github.com/prettier-solidity/prettier-plugin-solidity/issues/358
