### ISSUE TITLE
Backwards-incompatible changes in solidity-parser-antlr

### ISSUE THREAD

**Issue by federicobond** [prettier-solidity/prettier-plugin-solidity#199]
Hi there, I am testing [some fixes](https://github.com/federicobond/solidity-parser-antlr/commit/5e14b90d225758d132c99d0c307b7cf4813da5db) in the `stable` branch of `solidity-parser-antlr`, related to the way type name expressions are treated, as reported [here](https://github.com/federicobond/solidity-parser-antlr/issues/88). These changes are backwards incompatible.

I would love to get feedback and make the transition smooth to you folks once I publish the new version.

**Comment by fvictorio** [comment]
Hi @federicobond, thanks for letting us know!

So, I linked the stable branch of the `solidity-parser-antlr` and replaced all appearances of `ElementaryTypeNameExpression` with `TypeNameExpression`. Then I ran the tests and everything worked (just had to update some snapshots). Do you think that should be enough? If so, then I think you can proceed with publishing the new version —assuming is going to be a new major— and then we can update the dependency and make those changes. Does that make sense?

**Comment by federicobond** [comment]
Cool, thank you!

**Comment by mattiaerre** [comment]
thanks so much for the heads up @federicobond and thanks for verifying all the things @fvictorio 
🙏

**Comment by fvictorio** [comment]
@federicobond were these changes already published?

**Comment by Alonski** [comment]
Hey friends is this still an issue? Any chance someone could please take a look?

**Comment by mattiaerre** [comment]
I this it still is, no updates for `solidity-parser-antlr`

```bash
➜  prettier-plugin-solidity git:(master) npm view solidity-parser-antlr

solidity-parser-antlr@0.4.11 | MIT | deps: none | versions: 38
A Solidity parser built from a robust ANTLR 4 grammar
https://github.com/federicobond/solidity-parser-antlr

dist
.tarball: https://registry.npmjs.org/solidity-parser-antlr/-/solidity-parser-antlr-0.4.11.tgz
.shasum: af43e1f13b3b88309a875455f5d6e565b05ee5f1
.integrity: sha512-4jtxasNGmyC0midtjH/lTFPZYvTTUMy6agYcF+HoMnzW8+cqo3piFrINb4ZCzpPW+7tTVFCGa5ubP34zOzeuMg==
.unpackedSize: 900.9 kB

maintainers:
- federicobond <federicobond@gmail.com>

dist-tags:
latest: 0.4.11

published 2 months ago by federicobond <federicobond@gmail.com>
```

// cc @federicobond @fvictorio

**Comment by mattiaerre** [comment]
how about this one @fvictorio @Janther ?

**Comment by fvictorio** [comment]
I think we can close this one for the time being.
