### ISSUE TITLE
Running prettier doesnt do anything

### ISSUE THREAD

**Issue by HenryNguyen5** [prettier-solidity/prettier-plugin-solidity#206]
- Prettier version 1.18.2
- Plugin version 1.0.0-alpha.34

Running the plugin via the cli does nothing to change the files, even in invalid syntax files. Running the `-c` flag with prettier states that all the files have been properly formatted when they have not been

**Comment by josojo** [comment]
Hey,

are you running the command with the --write flag?
```
./node_modules/.bin/prettier --write contracts/**/*.sol
```

I really like this introduction from here: https://medium.com/coinmonks/introduction-to-solidity-linting-and-formatting-e838c074791a

**Comment by HenryNguyen5** [comment]
Hey @josojo, I have tested with the write flag and it didnt make a difference. The code I was trying to format was definitely unformatted so not sure whats going on. I did enable debug logging with prettier and it outputs that its resolving the plugin correctly per solidity file, it just doesnt do anything with it.

**Comment by HenryNguyen5** [comment]
This is totally my fault. I had `**/*.sol` in my `.prettierignore`
