### ISSUE TITLE
Option for FunctionDefinition: Always break parameters, visibility, stateMutability, modifiers and returnParameters

### ISSUE THREAD

**Issue by Wolf-Rost** [prettier-solidity/prettier-plugin-solidity#213]
Hi,

can you please provide two options for the function definition.

1. Option: Each parameter is always in a separate line if set to true.
2. Option: Each visibility, stateMutability, modifiers, and returnParameters are always in a separate line if set to true.

For instance:
```
function getContractAddress(uint256 id) public view isCurrentStates(State.ACTIVE, State.INACTIVE) returns (address)
{
     return _idToContractAddress[id];
}
```
will be prettified to
```
function getContractAddress(
    uint256 id
)
    public
    view
    isCurrentStates(State.ACTIVE, State.INACTIVE)
    returns (address)
{
    return _idToContractAddress[id];
}
```

Thank you very much

**Comment by fvictorio** [comment]
Hi @Wolf-Rost, thanks for the feedback.

I personally think that the less options, the better. That's also the philosophy of prettier-core. That being said, if enough people want this, I guess it's something that could be done. @mattiaerre @Janther what do you think?

**Comment by Janther** [comment]
I believe fewer options are better.

We could switch to break always but that seems a bit much in terms of opinion.

The option to break the parameters, if the modifiers break, is a bit complicated since the scopes are different.

**Comment by mattiaerre** [comment]
I agree w/ you @fvictorio and @Janther let's stick w/ what `prettier` does

**Comment by mattiaerre** [comment]
shall we close this issue @Wolf-Rost @fvictorio @Janther ?

**Comment by Janther** [comment]
Yes,
Fewer options is better and here we can afford to be opinionated.

**Comment by Wolf-Rost** [comment]
@mattiaerre Yup, the issue can be closed.
