### ISSUE TITLE
Thought: vscode solidity integration

### ISSUE THREAD

**Issue by juanfranblanco** [prettier-solidity/prettier-plugin-solidity#214]
Hi,

Happy new year. You have done an amazing job with the plugin to prettier, have you thought about having it fully integrated with the vscode solidity extension?

**Comment by fvictorio** [comment]
Hi @juanfranblanco and thanks!

What do you mean by having it fully integrated? There are some instructions in the readme on how to use it with VS (added in https://github.com/prettier-solidity/prettier-plugin-solidity/pull/200 for reference), but I'm not sure if that's what you're talking about.

**Comment by juanfranblanco** [comment]
Oh I mean, in the same way that the linters are included as part of the extension, to include prettier + the solidity plugin in the same way, so users can just press Ctrl + K and format the document instantly. Users this way just need to provide their preferences.

**Comment by fvictorio** [comment]
I think it's a great idea, just keep in mind that this project is still in an alpha stage. And if you need something done on our side, just comment it in this issue. (I don't want to speak for @mattiaerre and @Janther, but I guess they are probably OK with this too).

Please let us know after is done so we can update the readme with the proper instructions.

**Comment by mattiaerre** [comment]
of course @fvictorio and thanks @juanfranblanco we are more than happy to accept PRs we love OSS 😊

**Comment by juanfranblanco** [comment]
@mattiaerre @Janther @fvictorio I have added it now the plugin and prettier as the formatter for the vscode solidity extension https://github.com/juanfranblanco/vscode-solidity/blob/master/README.md#formatting-using-prettier-and-the-prettier-solidity-plugin and obviously all the credit to you https://github.com/juanfranblanco/vscode-solidity/blob/master/README.md#credits. 

Let's see how it goes for now I have included the functionality to only format per document using the context menu or Shift+Alt+F

**Comment by mattiaerre** [comment]
this is awesome, thanks so much @juanfranblanco we really appreciate that 🙏 how does it work for you? does it seem good enough?

**Comment by juanfranblanco** [comment]
It is working very well, and sure ill add more links :)

**Comment by Janther** [comment]
@juanfranblanco You might want to support `.prettierignore`.
at the moment the plugin is formatting our tests 🤣 which kinda beats the purpose of having them.

**Comment by juanfranblanco** [comment]
@Janther just seen this!! sure ill added it.

**Comment by juanfranblanco** [comment]
@Janther done, have a look

**Comment by mattiaerre** [comment]
I think we can close this issue right @juanfranblanco ?

**Comment by juanfranblanco** [comment]
@mattiaerre sure! Ill update the plugin in each release :)
