### ISSUE TITLE
Support for Solidity 0.6

### ISSUE THREAD

**Issue by fvictorio** [prettier-solidity/prettier-plugin-solidity#218]
Consensys forked and plans to maintain its own version of `solidity-parser-antlr` (discussion: https://github.com/federicobond/solidity-parser-antlr/issues/98). I'm not sure what Federico's plans are (not tagging his username to avoid spamming him).

At Solhint we are using a *temporary* fork I made, with both Consensys updates and some changes we needed: https://www.npmjs.com/package/@fvictorio/solidity-parser

Anyway, at some point we'll need to upgrade the parser. I opened this issue as a reminder and to explain the situation.

**Comment by mattiaerre** [comment]
uhm, that's interesting. I think we should be seriously considering using the Consensys version of the parser at this point. shall we spike that?

**Comment by fvictorio** [comment]
I think we should do that, yeah. If something changes later, it's not a big change to undo.

**Comment by mattiaerre** [comment]
@fvictorio please go ahead w/ a PR then
