### ISSUE TITLE
Handle `virtual` and `override` modifiers

### ISSUE THREAD

**Issue by fvictorio** [prettier-solidity/prettier-plugin-solidity#221]
This can't be done at the moment because the parser is not exposing this information. See https://github.com/ConsenSys/solidity-parser-antlr/issues/2

When that is solver, we should handle these modifiers.

`virtual` is easy: we should just add the literal `virtual` after the visibility modifier (at least that's where it's placed in the examples).

`override` might be followed by some class specifiers, so that should be handled properly. How to do it will depend on how the parser exposes this information.

**Comment by mattiaerre** [comment]
can we close this issue now @fvictorio ?

**Comment by Janther** [comment]
@mattiaerre `virtual` works but `override` is still not handled

**Comment by juanfranblanco** [comment]
Is there are workaround or setting to avoid prettier deleting keywords?

**Comment by Janther** [comment]
Our plugin reprints the code from the AST that we get from the parser.
Every keyword is handled by a different rule.
So is really difficult to predict how the parser will decide to implement each keyword or how the current parser will react to new syntax.
We are reactive in this sense. We have to wait until the parser evolves before we know how it will affect the printing process.
Currently the only way to avoid prettier to mess with an unsuported keyword is to add the comment `prettier-ignore` before the line. This will not avoid the parser trying to parse or even failing the parsing process, it will only tell prettier to choose the original text over the AST node.

**Comment by Janther** [comment]
if the problem continues the whole file could be skipped by adding it to `.prettierignore`

**Comment by juanfranblanco** [comment]
Ok thanks, I think I will disable it by default for the time being as I just had another issue, and let "advanced" users enable it themselves until things settle a bit. Keep the good work ! https://github.com/juanfranblanco/vscode-solidity/issues/168
