### ISSUE TITLE
Error: Comment "X" was not printed. Please report this error!

### ISSUE THREAD

**Issue by mcplums** [prettier-solidity/prettier-plugin-solidity#222]
So I'm just trying to run prettier on my contract here https://github.com/mcplums/Harber/blob/master/contracts/Harber.sol

but I get this error. Upon deleting the comment, the same error shows up for a different comment. It just does not like comments. I have had  a google and there are a couple of cases from a while ago just recommending an upgrade to prettier, but I have a much more recent version than required. As per package.json:

    "prettier": "^1.19.1",
    "prettier-plugin-solidity": "^1.0.0-alpha.37"

Wat do?

**Comment by Janther** [comment]
Hi @mcplums,

your scenario is known to us and I started working on it but hit a wall and the scenario is kinda rare, and even in prettier JS is treated as a specific case.

```Solidity
if (condition) {
  ...
} // comment about reason for else
else {
  ...
}
```

Prettier JS will do this:

```Solidity
if (condition) {
  ...
} else {
  // comment about reason for else
  ...
}
```

However, for us, this will create a change in the comments order in some scenarios. Which is difficult to predict and test.

I suggest that you make this change manually as it will require some effort to fix at the moment.

**Comment by mcplums** [comment]
Great, that makes sense, just a case of moving the comments inside the square brackets :) thanks for your help!
