### ISSUE TITLE
long tuple assignment formatted to single line

### ISSUE THREAD

**Issue by D2Edev** [prettier-solidity/prettier-plugin-solidity#225]
say, I have a long tuple declaration and assignment in solidity code.
It's convenient to have it formatted like long list of arguments for method - one method per line, i.e.:

`(string memory holderId,`  
`string memory containerId,`  
`string memory parentContainerId,`  
`bytes32 volumeId,`  
`bytes32 subUnitId,`  
`bytes32 requestId) = getParamsById(paramsId);`

But prettier-plugin converts tuple to single line, like:

`(string memory holderId,string memory containerId, string memory parentContainerId, bytes32 volumeId, bytes32 subUnitId, bytes32 requestId) = getParamsById(`  
`    paramsId`  
`);`

It even violates previously set line width, which makes it very uncomfortable to read.
Is there any setting for this or this is a bug/feature?

**Comment by fvictorio** [comment]
This is almost surely a bug. Thanks for reporting it!
