### ISSUE TITLE
Removed wrong keywords when auto-formatting 

### ISSUE THREAD

**Issue by juanfranblanco** [prettier-solidity/prettier-plugin-solidity#226]
The address payable keyword is wrongly corrected as address when using the helper contract Address.sol from OpenZeppelin. What I had in the smart contract was like

```using Address for address payable;```
But got wrongly auto-corrected as

```using Address for address;```

This issue was raised github.com/juanfranblanco/vscode-solidity/issues/162 by @maxweng

**Comment by mattiaerre** [comment]
thanks for reporting this @juanfranblanco it definitely sounds like a bug
