### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by Janther** [prettier-solidity/prettier-plugin-solidity#235]
I've been tinkering with the last cases for the coverage of our nodes and have found these 2 ones that I can't figure out.

- in [StateVariableDeclaration.js](https://github.com/prettier-solidity/prettier-plugin-solidity/blob/234790adc89f64c4384b7e97d88b2c88f5fe9c5b/src/nodes/StateVariableDeclaration.js#L12) we never print `', '` (not sure how to write multiple variables in one statement either)

- in [TupleExpression.js](https://github.com/prettier-solidity/prettier-plugin-solidity/blob/234790adc89f64c4384b7e97d88b2c88f5fe9c5b/src/nodes/TupleExpression.js#L21) there's never a case where `node` doesn't have a `components` key or does have an `elements` key.

Maybe the parser has taken care of these cases without us noticing??

My next PR will push the coverage to a :100:% in the `src/nodes` folder and I'm just missing these cases.

I'm happy to remove these conditionals now and add them back later if somebody finds the right way to trigger them.

**Comment by Janther** [comment]
[TupleExpression.js](https://github.com/prettier-solidity/prettier-plugin-solidity/blob/234790adc89f64c4384b7e97d88b2c88f5fe9c5b/src/nodes/TupleExpression.js#L30) has a `@TODO: remove hack once solidity-parser-antlr is fixed`.
My guess is that this was fixed and therefore, it's safe to remove.

Still would like to hear from the StateVariableDeclaration.js case.

**Comment by fvictorio** [comment]
I'm pretty sure you can't have multiple state variable declarations in the same statement (but you are the only real solidity dev here, so you surely know better :smile:) . Maybe it was done this way in the parser to be more future-proof?

**Comment by Janther** [comment]
I tried the tuple expression in this [comment](https://github.com/federicobond/solidity-parser-antlr/issues/14#issuecomment-347929306) in https://astexplorer.net and it uses `components` only and not `elements` as stated in that comment from 2017 so I feel it's safe to remove it.

Also since I couldn't really trigger that `', '` in StateVariableDeclaration and our tests are exhaustive so I'll be removing this in my next PR.
