### ISSUE TITLE
Inline assembly change in solidity 0.6: handle new representation for built-in opcodes such as `gas`

### ISSUE THREAD

**Issue by nicholaspai** [prettier-solidity/prettier-plugin-solidity#238]
[Solidity 0.6 Handles Inline Assembly opcodes differently](https://solidity.readthedocs.io/en/v0.6.0/assembly.html)

For example, `gas` is now `gas()`, which might be used in the smart contract method:

```
function _executeCall(address to, uint256 value, bytes memory data) private returns (bool success) {
        // Mostly copied from:
        // solhint-disable-next-line max-line-length
        // https://github.com/gnosis/safe-contracts/blob/59cfdaebcd8b87a0a32f87b50fead092c10d3a05/contracts/base/Executor.sol#L23-L31
        // solhint-disable-next-line no-inline-assembly

        // Ignoring this line for now because solidity 0.6 changed the "gas" instruction to "gas()", which prettier does not accept
        // prettier-ignore
        assembly {
            let inputData := add(data, 0x20)
            let inputDataSize := mload(data)
            success := call(gas(), to, value, inputData, inputDataSize, 0, 0)
        }
    }
```

Note that my current workaround is to just `prettier ignore` the entire AssemblyBlock

**Comment by fvictorio** [comment]
Does this mean that we should do different things if the `pragma` directive is >= 0.6? I don't think we have support for that, but it should be doable. This could also be an option in the prettier configuration, but that seems a little weird to me.

Thoughts @mattiaerre, @Janther?

**Comment by Janther** [comment]
Made a small PR handling this case.
I'm a bit unfamiliar with how developers behave in assembly but feel it's fine like this.
maybe someone could check the compiled code for both cases?

**Comment by nicholaspai** [comment]
> I'm a bit unfamiliar with how developers behave in assembly but feel it's fine like this.
> maybe someone could check the compiled code for both cases?

Nice work. Not entirely sure what you’re asking here, but as far as I can tell, they made opcodes that didn’t take arguments into zero-input “functions”

https://solidity.readthedocs.io/en/v0.6.0/assembly.html
https://solidity.readthedocs.io/en/v0.5.3/assembly.html

**Comment by fvictorio** [comment]
As far as I understand this, before 0.6 you could use either `gas` or `gas()`. In 0.6 you can only use `gas()`. Is this correct?

In that case, I think #239 correctly handles this and doesn't require handling different solidity versions: whether the user writes `gas` or `gas()`, it will be kept that way. If they write `gas` in a 0.6 file, it's the compiler's job to let them know that's not allowed.

**Comment by mattiaerre** [comment]
#239 has been merge, I'll publish a new version and then close this issue; thanks @Janther @fvictorio @nicholaspai

**Comment by nicholaspai** [comment]
Thanks @mattiaerre looks great

**Comment by mattiaerre** [comment]
and done!
