### ISSUE TITLE
Immutable keyword not supported

### ISSUE THREAD

**Issue by dileepfrog** [prettier-solidity/prettier-plugin-solidity#265]
Declaring an immutable storage variable:
```
uint256 immutable testVar;
```

Results in:
```
[error] contracts/Test.sol: ParserError: extraneous input 'testVar' expecting {';', '='} (136:20)
```

https://solidity.readthedocs.io/en/v0.6.5/miscellaneous.html#reserved-keywords

**Comment by mattiaerre** [comment]
thanks for reporting this bug @dileepfrog we'll take a look

**Comment by mattiaerre** [comment]
hi @dileepfrog a new version of the plugin has just been published; let us know if you have issues

prettier-plugin-solidity@1.0.0-alpha.50

**Comment by dileepfrog** [comment]
Working perfectly now, thank you for the quick fix!!
