### ISSUE TITLE
How to disable new line after if or else

### ISSUE THREAD

**Issue by avatar-lavventura** [prettier-solidity/prettier-plugin-solidity#268]
prettier-plugin-solidity converts

```
if <condition>
   revert()
```

into 

```if revert()```

----

Is it possible to disable this configuration?

**Comment by mattiaerre** [comment]
Hi @avatar-lavventura  you should be able to use `prettier-ignore` comments for that

https://prettier.io/docs/en/ignore.html

would this fix your issue?

**Comment by avatar-lavventura** [comment]
How could I enable it in the`.prettierrce` file as: ` "prettierIgnore": true` ?

**Comment by mattiaerre** [comment]
@fvictorio @Janther any idea?

**Comment by Janther** [comment]
can you give me more info about the environment in which you are running `prettier`?
These files are not used by us, but by prettier itself.

**Comment by fvictorio** [comment]
If you're asking if there's an option to change the behavior of prettier around this, the answer is no. There are options for other things, like single vs double quotes. But as a rule of thumb: is there's no equivalent option in prettier-js, then there's probably no option for that.

Closing this for maintenance purposes, but please re-open if that doesn't answer the question!

**Comment by avatar-lavventura** [comment]
My best option is to use brakets, this seems like ignores the changing behavior

```
if <condition> {
   revert()
}
```

**Comment by fvictorio** [comment]
Yes, I think the line joining only happens when there are no braces.
