### ISSUE TITLE
Extraneous newline between imports and contract

### ISSUE THREAD

**Issue by dileepfrog** [prettier-solidity/prettier-plugin-solidity#273]
Running the plugin at `1.0.0-alpha.50` on the following source:

```
pragma solidity ^0.6.5;

import { SafeMath } from '@openzeppelin/contracts/math/SafeMath.sol';

contract Test {
}
```

yields:

```
pragma solidity ^0.6.5;

import { SafeMath } from '@openzeppelin/contracts/math/SafeMath.sol';


contract Test {}
```

If I'm not mistaken, there should never be multiple consecutive newlines in the output

**Comment by mattiaerre** [comment]
I think you are right @dileepfrog we'll take a look

**Comment by Janther** [comment]
This has been one for discussion.

According to the [style guide](https://solidity.readthedocs.io/en/latest/style-guide.html#blank-lines) Top-level declarations should be surrounded with two blank lines.

Prettier will surround interfaces, contracts and library declarations with 2 lines.

Now struct declarations can be done as a top-level declaration as well, maybe we should consider adding this rule for that as well??

Anyway there are people in favour and against this rule and it's nice to have a discussion about this.

**Comment by dileepfrog** [comment]
Interesting, I did not notice that in the style guide before - thanks for linking. This seems to run contrary to Prettier's opinion [here](https://prettier.io/docs/en/rationale.html#empty-lines)

I notice in the docs however that there is only a single line between the `pragma` and the first contract declaration in the example, I'm guessing a typo?

**Comment by mattiaerre** [comment]
I personally like 1 blank line; how do you think we should proceed w/ this @Janther @fvictorio ?

**Comment by fvictorio** [comment]
I don't have a strong opinion on this.

In favor of 1 line:
- It's more aligned with what prettier-js does.
- Most contracts in the wild use one line AFAIK.

In favor of 2 lines:
- It's more aligned with the style guide.

If I have to choose, I choose 1 line, but then again it's not a strong preference.

**Comment by mattiaerre** [comment]
ok; I'll put a PR out w/ the 1 line option and see if we like it

**Comment by Janther** [comment]
naah I don't  think this deserves an option though usually I see at most 2 top level definitions in 1 file.

And the only place where I see more is when the programmer joins all the contracts into 1 massive file to validate it in https://etherscan.io

And even that now supports imports from multiple files.

I'd just go for a 1 liner between things

**Comment by dileepfrog** [comment]
If I can offer my $0.02, from the style guide:

```
Consistency with this style guide is important. Consistency within a project is more important.
```

Since prettier is a JS tool and this plugin is likely used in a JS-based project using prevalent ecosystem tools like Truffle or ethers.js, being consistent with the 1 liner across all source files would make more sense.

**Comment by PaulRBerg** [comment]
One more vote for 1 line!
