### ISSUE TITLE
Support `virtual` and `override` for modifiers.

### ISSUE THREAD

**Issue by petejkim** [prettier-solidity/prettier-plugin-solidity#279]
Currently it works for functions, but not for modifiers.

Example:

```solidity
modifier onlyOwner() virtual;

modifier onlyOwner() override {
    require(msg.sender == owner(), "Ownable: caller is not the owner");
    _;
}
```

**Comment by Janther** [comment]
I'll fix this.
By the way, virtual keyword in modifiers is described like this in the [docs](https://solidity.readthedocs.io/en/v0.6.8/contracts.html#index-18)
```Solidity
modifier onlyOwner() virtual {_;}
```

**Comment by Janther** [comment]
@fvictorio can you update the parser to add the `virtual` and `override` information to the modifiers, please?

**Comment by fvictorio** [comment]
`@solidity-parser/parser@0.6.2` adds this. Sorry for taking so long to add it!
