### ISSUE TITLE
indent guides for some .sol files are shown for 4 spaces while on other files as 2 spaces

### ISSUE THREAD

**Issue by zemse** [prettier-solidity/prettier-plugin-solidity#285]
For some `.sol` files the tabSize is 4, while for some `.sol` files the tabSize is 2. I tried restarting the editor and it seems to recall which files were showing tabSize 4 and which tabSize 2. 

![Screenshot 2020-06-02 19 08 07](https://user-images.githubusercontent.com/22412996/83526911-b9919700-a504-11ea-9d5c-c36f1ee8ff58.png)

![Screenshot 2020-06-02 19 09 10](https://user-images.githubusercontent.com/22412996/83526953-c615ef80-a504-11ea-8ef4-c04964e98556.png)

My `.prettierrc` file:

```
{
  "overrides": [
    {
      "files": "*.sol",
      "options": {
        "printWidth": 80,
        "tabWidth": 4,
        "useTabs": false,
        "singleQuote": false,
        "bracketSpacing": true,
        "explicitTypes": "always"
      }
    }
  ]
}

```

If I use `useTabs: true`, then it looks like in one file there are less tab space and in other file there is more tab space.

The overide `"files": "*.sol"` does match all the sol files, I checked by flipping `singleQuote` and the quotes are consistent over all the solidity files. The issue is just with the `tabSize`, in some files it is 2 while in some files it is 4.

Versions:
```
"prettier": "^2.0.5",
"prettier-plugin-solidity": "^1.0.0-alpha.53"
```

**Comment by zemse** [comment]
Guys I fixed this using the following in the settings.json:
```javascript
"[solidity]": {
  "editor.detectIndentation": false,
  "editor.tabSize": 4,
}
```

If this problem is reproducible to anyone? 
Can these settings be set with the plugin?

**Comment by mattiaerre** [comment]
hi @zemse I'm assuming you are using VSCode, did you try to check the README?

https://github.com/prettier-solidity/prettier-plugin-solidity#vscode

**Comment by Janther** [comment]
We need to update the README since the `vscode-solidiy` plugin does most of the work now.
@zemse I have never seen this problem. Usually, the editor defines what rules of indentation will be applied by looking at the file and check for the first indentation. However `prettier` has no clue on this variable, so whenever the file it's saved, prettier will take over and insert 4 spaces unless you add a prettier specific configuration.
Is it possible for you to share a link to the project to have a look?

**Comment by fvictorio** [comment]
Notice that `prettier` detects and respects `.editorconfig` (just tried it). So this seems like a problem with the VSCode plugin.

If you want to double check this:

```
$ echo 'function foo() { return 1; }' > foo.js
$ cat > .editorconfig << EOF
root = true

[*]
indent_size = 6
EOF
$ prettier foo.js
function foo() {
      return 1;
}
```

**Comment by fvictorio** [comment]
I'm not sure I understood your comment since I don't use VS Code, but PRs are of course welcome!

**Comment by mattiaerre** [comment]
> I'm not sure I understood your comment since I don't use VS Code, but PRs are of course welcome!

ditto!

**Comment by fvictorio** [comment]
I think this is no longer an issue? Please re-open if that's the case.
