### ISSUE TITLE
AssemblyFunctionDefinition is not entirely correct

### ISSUE THREAD

**Issue by kfichter** [prettier-solidity/prettier-plugin-solidity#305]
Hello! Just noticed this while prettifying a contract with a function inside an assembly block. Current definition at [`AssemblyFunctionDefinition`](https://github.com/prettier-solidity/prettier-plugin-solidity/blob/master/src/nodes/AssemblyFunctionDefinition.js) expects all functions to have return values (`-> ret`). As a result, the plugin erroneously inserts `-> ` in cases where a function has no return value. 

Ex.:

```
function $somefn(somearg) {
    // do something
}
```

is converted into

```
function $somefn(somearg) ->  {
    // do something
}
```

For now I'm simply inserting a dummy return value, but I'm creating this issue because it seems like a simple fix.

Thank you for your hard work on this project!

**Comment by fvictorio** [comment]
Hey @kfichter, thanks for reporting this!

I opened a PR that fixes this problem. You can check the snapshot with the before and after [here](https://github.com/prettier-solidity/prettier-plugin-solidity/pull/306/files#diff-fd0755d51e12f7cc742b09bc337d2c51) Do you think that's enough? Is there another scenario that should be considered around this?

**Comment by kfichter** [comment]
@fvictorio Looks good to me! Thank you!
