### ISSUE TITLE
Support solidity 0.7.0

### ISSUE THREAD

**Issue by junderw** [prettier-solidity/prettier-plugin-solidity#310]
`Constructors have to be declared either "public"` rule is now the opposite.

non-abstract contracts with Constructors must NOT have public or internal.

**Comment by fvictorio** [comment]
This is a problem in the parser. I will open an issue upstream. Thanks for reporting it!

**Comment by fvictorio** [comment]
This should be fixed after https://github.com/solidity-parser/parser/issues/23

**Comment by junderw** [comment]
Also, for this repository in specific, it seems as though by default it automatically adds public when I use `--write`

Perhaps we could add an option to not add the public to constructors.

**Comment by junderw** [comment]
https://github.com/prettier-solidity/prettier-plugin-solidity/compare/master...junderw:master

My branch (not sure if this is the best way to stop it from adding public)

**Comment by fvictorio** [comment]
See #311, I think it just worked out of the box. Maybe it didn't work for you before when you were setting it to `public`, but setting it to `default` seems to do the trick.

**Comment by fvictorio** [comment]
Oh, wait, you mean adding it when it's not present? That's not something we do because we don't make any modification that changes the AST.

**Comment by junderw** [comment]
LGTM

ahhh, I think the problem was I was initially setting visibility to "public" in the else case. if "default" it should be fine.

**Comment by zemse** [comment]
Hi, is there any update when the linked PR would be merged and a release (or pre-release) be available? Or is it already available? 

I've been very much used to running prettier on save and it would be very convenient if even a pre-release is avaiable like OpenZepplin have done `"@openzeppelin/contracts": "^3.1.0-solc-0.7",`

**Comment by junderw** [comment]
In the meantime, I have published a single version package that includes this change, however, the package name needs to stay the same or things break, so you can install it like this:

`npm install prettier-plugin-solidity@npm:junderw-prettier-plugin-solidity@1.0.0-alpha.56`

It's weird, it's saying "install junderw-prettier-plugin-solidity@1.0.0-alpha.56 from npm, but refer to it within the project as prettier-plugin-solidity"...

Anywho, I will only have that one version published, and I won't maintain it.

**Comment by fvictorio** [comment]
`1.0.0-alpha.56` should support 0.7.0 now
