### ISSUE TITLE
Error when ignoring function declaration inside a struct and adding a comment.

### ISSUE THREAD

**Issue by adjicf** [prettier-solidity/prettier-plugin-solidity#326]
Function type declaration are rewritten incorrectly and when ignoring them and adding some comments there is another extra error.

**The original code:**
```
contract Broken {
    struct Something {
        // This gives an error
        function (address) external view returns (uint256) getSomething;
    }
}
```

When ignoring it:
```
contract Broken {
    // prettier-ignore
    struct Something {
        // This gives an error
        function (address) external view returns (uint256) getSomething;
    }
}
```

**The error:**
contracts/Broken.sol: Error: Comment "This gives an error" was not printed. Please report this error!
[error]     at astComments.forEach.comment (...../contracts/node_modules/prettier/index.js:14273:13)
[error]     at Array.forEach (<anonymous>)
[error]     at Object.ensureAllCommentsPrinted (contracts/node_modules/prettier/index.js:14271:15)
[error]     at coreFormat (...../contracts/node_modules/prettier/index.js:14858:12)
[error]     at format (...../contracts/node_modules/prettier/index.js:15063:14)
[error]     at formatWithCursor (...../contracts/node_modules/prettier/index.js:15080:12)
[error]     at Object.args [as formatWithCursor] (...../contracts/node_modules/prettier/index.js:54658:12)
[error]     at format (...../contracts/node_modules/prettier/bin-prettier.js:15851:14)
[error]     at Object.formatFiles (...../contracts/node_modules/prettier/bin-prettier.js:16035:16)
[error]     at Object.run (...../contracts/node_modules/prettier/bin-prettier.js:16508:14)

**Comment by mattiaerre** [comment]
thanks for reporting this @adjicf

**Comment by fvictorio** [comment]
This seems to be fixed in the latest version. @adjicf please re-open if that's not the case.
