### ISSUE TITLE
Don't replace `uint` with `uint256`

### ISSUE THREAD

**Issue by fvictorio** [prettier-solidity/prettier-plugin-solidity#341]
This won't beak anything, but it's not a good idea IMO. Of course, this also applies to other types that have a default size (like `int`).

**Comment by Janther** [comment]
There's an option for that called [explicitTypes](https://github.com/prettier-solidity/prettier-plugin-solidity/blob/a30211d1bf29c767dad11f84d9d1b2944426d5e9/src/options.js#L51).
I added this to the formatter after verifying that the compiler creates the same byte code with either option.

**Comment by fvictorio** [comment]
Ohh, I missed that! That's very cool, I like it :smiley:
