### ISSUE TITLE
Issue when parsing files with numbers like 100_000

### ISSUE THREAD

**Issue by Macarse** [prettier-solidity/prettier-plugin-solidity#355]
There is an issue parsing numbers with underscores, for example 100_000.
To repro:
```
pragma solidity 0.6.12;

contract Bug {
  // This is a comment
  uint public hello;

  // Another comment
  uint public bigNum = 100_000;

  // This will disappear
  uint public magic;
}
```

Output:
```
pragma solidity 0.6.12;

contract Bug {
    // This is a comment
    uint256 public hello;

    // Another comment
    uint256 public bigNum = 100_000;

    uint256 public magic;
}
```

Comments will be removed after the `_` and as you can see `  // This will disappear` went away.

Versions:
```
"prettier": "^2.1.2",
"prettier-plugin-solidity": "^1.0.0-alpha.58"
```

**Comment by fvictorio** [comment]
This is a problem with [`extract-comments`](https://github.com/jonschlinkert/extract-comments). We could open an issue there but... I think it's not a good idea to be using a _javascript_ comment extractor for a solidity project.

I think the proper solution here is to write a comment extractor for solidity. It shouldn't be that hard.
