### ISSUE TITLE
It possible to use `ESLint` in parallel to `prettier-plugin-solidity` ?

### ISSUE THREAD

**Issue by avatar-lavventura** [prettier-solidity/prettier-plugin-solidity#365]
@fvictorio This issue is related to [How to disable new line after if or else ?](https://github.com/prettier-solidity/prettier-plugin-solidity/issues/268). 

On [prettier issues](https://github.com/prettier/prettier/issues/9460#issuecomment-713409891) @kachkaev  responded me as:

> If you are also using ESLint in parallel to Prettier, you can force curly braces via https://eslint.org/docs/rules/curly
>
> You can find my personal opinionated example in https://github.com/kachkaev/njt. The repo uses ESLint for JS/TS/JSON and Prettier for JS/TS/JSON/Markdown/YAML. Things are pretty much aligned with the Prettier’s philosophy.

---

=> An an alternative solution is It possible to use `ESLint` in parallel to `prettier-plugin-solidity` ?

**Comment by fvictorio** [comment]
You mean for linting? I don't think you can use eslint for solidity, it's a different language.

You can use [solhint](https://github.com/protofire/solhint/) for that. As far as I can remember, there's no rule for what you want (forcing braces in all ifs, right?), but it should be easy to add one.
