### ISSUE TITLE
VSCode Save on format not working on some .sol files

### ISSUE THREAD

**Issue by Suedo** [prettier-solidity/prettier-plugin-solidity#380]
I have three `.sol` files in my project, two of them get formatted on save in vs code, while the third one does not. 

Below snippet from the bad file does not formatted on save:
```js
  function tryClosing() public returns (bool) {
      require(totalCollected >= targetAmount, "Amount not met"); // this extra indent is not fixed by prettier in this one file
    require(block.timestamp > fundingDeadline, "Time left");
    status = Status.Succeeded;
    return true;
  }
```

But in another file, extra indent gets auto fixed on save
```js
  receive() external payable {
      balances[msg.sender] += msg.value; // putting an extra indent here is auto fixed
    emit Received(msg.sender, msg.value, balances[msg.sender]);
  }
```

Any idea why I might be facing such weird issues?

I am in a WSL Ubuntu remote in VS Code

**Comment by fvictorio** [comment]
Hi @Suedo, I don't use VS Code but, if it is a problem with the plugin itself (and not with the VS Code extensions you are using), you should be able to reproduce it by running prettier from the command line on that file. If that gives you an error, please let us know. The snippet you shared works fine, but maybe the whole file triggers the issue?

**Comment by gigamesh** [comment]
I'm able to format with the command line but not format-on-save, so is it safe to assume there is a problem with the [vscode-solidity](https://github.com/juanfranblanco/vscode-solidity) plugin?

btw, I had to explicitly add the plugin to my .prettierrc plugins list to get it to work via command line. I'm happy to make a PR if you'd like that added to the README instructions.

**Comment by fvictorio** [comment]
Honestly I'm not really sure how that works. Sometimes I had to add it, sometimes I didn't. I will check prettier's docs to see how that is supposed to work.

**Comment by fvictorio** [comment]
Closing this one for bookkeeping. If someone has an issue with vscode and our plugin, please let us know.
