### ISSUE TITLE
[Suggestion] Don't join string literals that are split

### ISSUE THREAD

**Issue by junderw** [prettier-solidity/prettier-plugin-solidity#391]
Edit: (Related: https://github.com/solidity-parser/parser/issues/32 this is required to allow hex literals to have the same formatting)

I have a 148 character long string that is hard to look at in the source code. So I've split it using multi-line and prettier-ignore

Similar to JavaScript prettier, if I write a string as `'abc' + 'def'` than it tends to format things nicer than when I keep everything as one long string, the format process feels free to play around with my "chunks" and their position to make the "prettiest" format.

Currently split strings get joined.

Example:

```solidity
string memory a = 'abc'
                    'def'
          'ghi';
```

Current Result:

```solidity
string memory a = 'abcdefghi';
```

Suggestion:

```solidity
string memory a = 'abc'
    'def'
    'ghi';
```

Or maybe have them be same line unless going over a certain length:

```solidity
// assume including the ghi chunk would put it over the one line length limit.
string memory a = 'abcdef'
    'ghi';
// OR
string memory a = 'abc' 'def'
    'ghi';
```

**Comment by fvictorio** [comment]
Thanks @junderw, I'll take a look as soon as I can.

I'm not sure what the best solution is here. I'm inclined to think that we should never join them, and then split them over several lines if they (concatenated with spaces) don't fit in one line.

Examples:

```
// fits in one line
string memory a = "foo" "bar" "baz"
```

```
// doesn't fit in one line
string memory a = 
  "foo"
  "bar"
  "baz"
  "qux"
```

**Comment by junderw** [comment]
I'm more of a "first line goes on same line as =" type of guy.

```solidity
// doesn't fit in one line
string memory a = "foo"
  "bar"
  "baz"
  "qux";
```

Also, I raised an issue on the parser as well, when split string literal support was added, hex literal support was not.

If strings and hex literals all behaved in someway similar to what you proposed or my suggestion I would be happy.

**Comment by fvictorio** [comment]
I think that would be a little inconsistent. For example:

```
string memory a =
  "a very very very very long line"

uint[] array = [
  1,
  2,
  3
]
````

While the opening brace is in the same line, in that case it's just syntax, the values are still below.

Very subjective and probably there's not a right answer. I wonder if there's a similar javascript example to check what prettier-js does.

**Comment by junderw** [comment]
Looks like you were right @fvictorio 

Looks like this:

```js
const a = 'abc' +
       'def' + 'ghi' +
'jkl';
```

Becomes

```js
const a = "abc" + "def" + "ghi" + "jkl";
```

But

```js
const a = 'abcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' +
       'def' + 'ghi' +
'jkl';
```

Becomes

```js
const a =
  "abcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" + "def" + "ghi" + "jkl";
```

And

```js
const a = 'abcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' +
       'def' + 'ghi' +
'jkl';
```

Becomes

```js
const a =
  "abcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" +
  "def" +
  "ghi" +
  "jkl";
```

**Comment by junderw** [comment]
Related issue: (HexLiteral support in the parser to allow for the same multiline formatting for hex literals)

https://github.com/solidity-parser/parser/issues/32
