### ISSUE TITLE
Chained field access and method calls

### ISSUE THREAD

**Issue by fvictorio** [prettier-solidity/prettier-plugin-solidity#399]
One area where we are not doing a great job is in chained calls, things like:

```solidity
foo.bar.baz().qux.quux()
```

This should be split in a nice way when the line is long enough. Any change here needs to take some things into consideration:

1. Does the strategy changes if we are in an assignement? For example:

    ```solidity
    uint x = foo.veryLongMethod().veryVeryLongMethod()
    ```

    could be either

    ```solidity
    uint x = 
      foo.veryLongMethod().veryVeryLongMethod()
    ```

    or

    ```solidity
    uint x = foo
      .veryLongMethod()
      .veryVeryLongMethod()
    ```

    Is the second option always used? Or is the first one tried and if that isn't enough, the second one is used? As always, the approach here is: see what prettier-js does, try several combinations, generate tests for us based on that, and then implement.

2. Are method calls and field accesses treated the same, or are they handled differently? The answer is the same one as before: steal from prettier-js. Here's an example of how they handle this:

    ```js
    const a = o.veryVeryLongField
    
    const b = o.veryVeryLongMethod()
    
    const c = o.veryVeryLongField.anotherField.aMethod().yetAnotherField
    
    const d = o.veryVeryLongMethod().aField.anotherField().anotherMethod().finalField
    ```

    with a print width of 20 becomes

    ```js
    const a =
      o.veryVeryLongField;
    
    const b = o.veryVeryLongMethod();
    
    const c = o.veryVeryLongField.anotherField.aMethod()
      .yetAnotherField;
    
    const d = o
      .veryVeryLongMethod()
      .aField.anotherField()
      .anotherMethod()
      .finalField;
    ```

    as you can see, fields and methods change how things are done.

This should be more than enough to start working on this, but there are probably a lot of edge cases that will only surface when more projects start using this formatter. For now, let's just do something pretty enough in these basic scenarios.

**Comment by mattiaerre** [comment]
I'm classifying this as an enhancement, what do you think @fvictorio ?

**Comment by frangio** [comment]
@fvictorio Here's an example from OpenZeppelin Contracts that looks pretty awkward. Note the indentation in `.recover`. (Line length is set to 120.)

```solidity
function verify(ForwardRequest calldata req, bytes calldata signature) public view returns (bool) {
    address signer =
        _hashTypedDataV4(
            keccak256(abi.encode(TYPEHASH, req.from, req.to, req.value, req.gas, req.nonce, keccak256(req.data)))
        )
            .recover(signature);
    return _nonces[req.from] == req.nonce && signer == req.from;
}
```

This is what Prettier spits out for similar TypeScript code:

```typescript
function verify(req: ForwardRequest, signature: bytes): boolean {
  const signer: address = _hashTypedDataV4(
    keccak256(abi.encode(TYPEHASH, req.from, req.to, req.value, req.gas, req.nonce, keccak256(req.data)))
  ).recover(signature);
  return _nonces[req.from] == req.nonce && signer == req.from;
}
```

**Comment by Janther** [comment]
@frangio thank you for this one. I knew I had seen something like this but couldn't quite replicate it.
This has multiple moving parts though. I'll see how I can tackle this one.

**Comment by Janther** [comment]
Wow doing this `a(...).b` has been proven quite the challenge when the contents of `a` break the line since from `b` I can't really know if that happened so is really difficult now to pinpoint which to choose.
```
a(...).b

a(...)
  .b

a(
  ...
).b
```
please consider that these chains can be really long

**Comment by fvictorio** [comment]
This is prettier's output with a lower print-width:

```typescript
function verify(req: ForwardRequest, signature: bytes): boolean {
  const signer: address = _hashTypedDataV4(
    keccak256(
      abi.encode(
        TYPEHASH,
        req.from,
        req.to,
        req.value,
        req.gas,
        req.nonce,
        keccak256(req.data)
      )
    )
  ).recover(signature);
  return _nonces[req.from] == req.nonce && signer == req.from;
}
```

**Comment by frangio** [comment]
Is it possible to ask at .b whether you're at the beginning of a new line?

**Comment by Janther** [comment]
Prettier is the one building the final file, we give some general instructions on how to build the file. `.b` has no idea where it will finish so we have to cater for the possibilities and let Prettier find the best option. Of course we can also restrict the rules given the context of the situation thus forcing Prettier to only have one option and here is where I am right now.

I'm giving this part a bit of a full rewriting, not as naive as the one we had when building `alpha` but with more tools and better knowledge on how to proceed.

One of my findings was that everything in the chain depends on whether the first section of the chain breaks or not.

**Comment by frangio** [comment]
@Janther Awesome! Thank you for the update. Will give it a shot again once this one is fixed.

**Comment by Janther** [comment]
@frangio can you try with the latest version?
Don't forget to update prettier to `^2.3.0`.

**Comment by frangio** [comment]
@Janther Awesome work! Looks great to me.

**Comment by Janther** [comment]
this has been redone completely and the latest version prints chains in a satisfying way.
