### ISSUE TITLE
keyword `unchecked` breaks parsing

### ISSUE THREAD

**Issue by NoahZinsmeister** [prettier-solidity/prettier-plugin-solidity#409]
Using the keyword `unchecked` in solidity >=0.8.0 causes parsing errors (e.g. `Error: missing ';' at '{'`).

Minimal example:

```
function mul(uint256 x, uint256 y) internal pure returns (uint256) {
  unchecked { return x * y; }
}
```

**Comment by fvictorio** [comment]
Hey Noah, thanks for opening this. I need to fix this in the parser first (https://github.com/solidity-parser/parser/issues/36) and then I'll add support for this here.

**Comment by fvictorio** [comment]
@NoahZinsmeister #416 should fix this. If you want to give it a try before it's published, change your installed version to:

```
    "prettier-plugin-solidity": "prettier-solidity/prettier-plugin-solidity#unchecked-blocks"
```
