### ISSUE TITLE
Update js dependencies

### ISSUE THREAD

**Issue by Janther** [prettier-solidity/prettier-plugin-solidity#421]
`@babel/ployfill` is been deprecated and `axios` has solved a critical security issue in the latest version.

**Comment by mattiaerre** [comment]
hi @Janther I don't think we use these packages. can you help me to find out where they are listed?

**Comment by Janther** [comment]
`axios` is a Promise based HTTP client for the browser and node.js, it wraps HTTP calls to the server and provides a nice way to handle errors or successes.

`@babel/ployfill` provides all of the features of ES2015+ to plain js. most of our coding style in js is based in js16 and definitely the VUE templates are transpiled into js16 or higher. Current browsers can handle most of the new features but they are behind in a few, `@babel/ployfill` checks our targeted browsers and adds a few functions to the bundle that will tell the browser how to run a specific syntax

These dependencies are in the `package.json` file.

**Comment by Janther** [comment]
wow wrong
