### ISSUE TITLE
I've got a list of recommendations on how to format code for security / readability

### ISSUE THREAD

**Issue by thegostep** [prettier-solidity/prettier-plugin-solidity#427]
- [ ] don't use contract types in variable declarations
- [ ] declare interfaces in the contract file and override
- [ ] declare all storage variables as private
- [ ] use _ prefix for private / internal references instead of for function parameters
- [ ] organize contract files by access control and state mutability
- [ ] use immutable variables or registry instead of hardcoding addresses
- [ ] move events to interfaces
- [ ] move enums to interfaces
- [ ] use explicit inheritance function references

**Comment by Janther** [comment]
Thank you for this.
I would suggest your feedback would be a better fit for a linter like [solhint](https://protofire.github.io/solhint/).
This project focuses only on being opinionated and keeping the **format** consistent across the code. Your suggestions would fall in the best practices category.

**Comment by mattiaerre** [comment]
thanks @thegostep for the suggestions but I'd agree w/ @Janther this may be a better fit for a linter project. I'd be inclined to close this issue if that's ok
