### ISSUE TITLE
Fails when a function has only a comment

### ISSUE THREAD

**Issue by fvictorio** [prettier-solidity/prettier-plugin-solidity#45]
If a function has only a comment as body:

```solidity
function foo() public {
  // to be defined
}
```

prettier fails with a `Comment "to be defined" was not printed.`

I created a branch https://github.com/prettier-solidity/prettier-plugin-solidity/tree/function-body-with-comment that has a failing test.

**Comment by j-f1** [comment]
I’m not really familiar with the comment part of Prettier unfortunately.
