### ISSUE TITLE
Errors in for statements

### ISSUE THREAD

**Issue by fvictorio** [prettier-solidity/prettier-plugin-solidity#46]
A for statement like this:

```solidity
for (uint256 i = 0; i < 10; i++) {}
````

is formatted as:

```solidity
  for (uint256 i = 0;i < 10; i++;) {

  }}
```

Things to notice:

1. The closing brace is duplicated and an extra semicolon is added after the loop condition. Both of these things cause syntax errors.
2. There is no space after the first semicolon.

I think this is a blocker (hopefully the last one) for publishing an alpha version.

**Comment by mattiaerre** [comment]
Thanks for this @fvictorio I was looking into the issue and I have a branch w/ a kind of a fix. The problem is in the `ForStatement` as well as the `ExpressionStatement`; I'll open a PR w/ a new contract (that has got a for loop) so that you can verify what's going on.
