### ISSUE TITLE
printWidth not working

### ISSUE THREAD

**Issue by ilanolkies** [prettier-solidity/prettier-plugin-solidity#479]
Hi!

I am using the prettier plugin and I set the option `printWidth` but it does not affect how my contracts are printed. I have this contract as an example https://github.com/rsksmart/erc677/pull/9/files#diff-1d453ec07aae7bd16a3421971223de25446c0a0c7ea5c5605ca7c43b5439e832

Thanks!

**Comment by fvictorio** [comment]
Hi @ilanolkies. That `.prettierrc.json` works for me in a simple project, so maybe it's something related to your setup? If you can make a minimal reproducible example, I can take a look.

**Comment by Janther** [comment]
It looks like the thing that you might be expecting is for the function definitions to be printed in one line.
This has been part of an ongoing discussion for us right now we are forcing the declaration to split if the function accepts more than 2 parameters, regardless of the length.
If you want to contribute to this conversation and help us reach a consensus on what the community would benefit more have a look here #474

**Comment by mattiaerre** [comment]
so it looks like this is not an issue then? can we close it @ilanolkies ?

**Comment by ilanolkies** [comment]
Thanks! Sorry I didn’t send the example. It is a function with more than two params.
