### ISSUE TITLE
Add support for error definition

### ISSUE THREAD

**Issue by alejoamiras** [prettier-solidity/prettier-plugin-solidity#485]
https://docs.soliditylang.org/en/v0.8.4/control-structures.html?highlight=revert#error-handling-assert-require-revert-and-exceptions

Solidity now supports the creation of errors, to add syntax for stuff like:
```solidity
error Unauthorized();
if (!authorized()) revert Unauthorized()
```

Prettier throws:
`Error: mismatched input '(' expecting {';', '='}` on the `error Unauthorized()` line.

**Comment by fvictorio** [comment]
Relevant issue in the parser: https://github.com/solidity-parser/parser/issues/45

**Comment by mattiaerre** [comment]
is this something we should/could fix on our end @fvictorio or not really?

**Comment by fvictorio** [comment]
@mattiaerre I'm the one maintaining that parser, so I just need to implement it :sweat_smile: I will comment here when it's ready.

**Comment by mattiaerre** [comment]
thanks @fvictorio 😊

**Comment by dileepfrog** [comment]
I have been waiting for this feature in Solidity for many moons, can't wait to have Prettier support for it as well!
