### ISSUE TITLE
prettier-plugin-solidity creates and error when using the syntax "using SafeMath for uint256;"

### ISSUE THREAD

**Issue by adnfx2** [prettier-solidity/prettier-plugin-solidity#494]
Whenever I use the syntax "using SafeMath for uint256;" I got an error from prettier, If I delete/comment this line from the file everything goes back to normal, I tried to use "// prettier-ignore" but this trick didn't work.

I'll leave an image where I called prettier to format a solidity file from the command line and got an output error msg:

![solidity error](https://i.imgur.com/6U1SCYv_d.webp?maxwidth=1520&amp;fidelity=grand)

**Comment by adnfx2** [comment]
My apologies for opening this issue, it was a silly mistake made by me. 

The "using SafeMath for uint256" syntax was outside of the contract block and this is wrong :x: : 
```solidity
pragma solidity ^0.5.0;

import "./safemath.sol";

using SafeMath for uint256;  // Oops this is a mistake 

contract{
    // some contract
}
```
Instead it should go inside of the contract block :heavy_check_mark: :
```solidity
pragma solidity ^0.5.0;

import "./safemath.sol";

contract{
    using SafeMath for uint256;  // This is correct!!

    // some contract
}
```

 After making the proper changes everything started to work as intended back again.

**Comment by mattiaerre** [comment]
thanks for keeping us in the loop @adnfx2 and for closing this issue too 😊
