### ISSUE TITLE
Enum variants reformatted to one line

### ISSUE THREAD

**Issue by frangio** [prettier-solidity/prettier-plugin-solidity#508]
Running prettier results in the following change:

```diff
-    enum Error {
-        None,
-        RevertWithMessage,
-        RevertWithoutMessage,
-        Panic
-    }
+    enum Error {None, RevertWithMessage, RevertWithoutMessage, Panic}

```

I would expect enum variants to remain each in its own line. This is what Prettier seems to do for TypeScript variants as well.

**Comment by fvictorio** [comment]
Thanks @frangio for this and the rest of the issues. We'll try to fix them as soon as we can.
