### ISSUE TITLE
Indentation of case statements in assembly

### ISSUE THREAD

**Issue by frangio** [prettier-solidity/prettier-plugin-solidity#509]
Prettier indents `case` statements in assembly blocks (i.e. one more indentation level than the corresponding `switch`). This was mentioned in [#92](https://github.com/prettier-solidity/prettier-plugin-solidity/pull/92/files#r245526124) as desirable, but I'd disagree for two reasons:

1. Even though `case` is indented by Prettier in JavaScript, this doesn't translate well to Solidity because in JavaScript `switch` blocks are wrapped in braces, which is IMO what justifies the extra indentation.

```javascript
switch (x) {
  case 0: ...
  case 1: ...
}
```

2. [In Solidity documentation](https://docs.soliditylang.org/en/latest/yul.html#switch) `switch` and `case` are written at the same indentation level:

```solidity
{
    let x := 0
    switch calldataload(4)
    case 0 {
        x := calldataload(0x24)
    }
    default {
        x := calldataload(0x44)
    }
    sstore(0, div(x, 2))
}
```

**Comment by fvictorio** [comment]
I _just_ saw that gofmt does this too (switch and case lines at the same level) and thought it was pretty cool, so I'm OK with this.
