### ISSUE TITLE
Bug: Virtual is removed in fallback and receive

### ISSUE THREAD

**Issue by frangio** [prettier-solidity/prettier-plugin-solidity#510]
Prettier removes `virtual` modifier from `fallback` and `receive` functions.

```diff
- fallback() external payable virtual {
+ fallback() external payable {
```

Note: `virtual` is important here and changes whether child contracts can override the fallback or not.

**Comment by fvictorio** [comment]
This is a terrible bug. We should check why the bytecode comparison tests didn't catch it.

**Comment by Janther** [comment]
@fvictorio did some digging the parser is not giving us the `isVirtual` value that we use to print the keyword.

**Comment by fvictorio** [comment]
Oh damn, I'll fix it right now.
