### ISSUE TITLE
Make a single `parser.visit` call in the `src/parser.js` module

### ISSUE THREAD

**Issue by fvictorio** [prettier-solidity/prettier-plugin-solidity#538]
Right now the parser module does many `parser.visit` calls. This means that the whole AST is traversed each time, with different visitor trees. This is unnecessarily wasteful. I'm not a fan of optimizing performance without benchmarks, but in this case the change is trivial (doing a single `parser.visit` call and "merging" the visitor objects) and I'm sure it will have a positive impact.

**Comment by Janther** [comment]
Closing since we only visit once in our `main` branch. Multiple visits was something I was checking out in a PR and will undo.
