### ISSUE TITLE
Error: The specified node does not exist

### ISSUE THREAD

**Issue by SvenMeyer** [prettier-solidity/prettier-plugin-solidity#541]
prettier failed with no useful error message because I had a semicolon instead of a comma after one argument in a long list of constructor arguments !

Any chance to improve that ?

https://github.com/paulrberg/solidity-template/issues/47

**Comment by fvictorio** [comment]
I just tried formatting this:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.0;

contract Foo {
  constructor(
    uint a,
    uint b;
    uint c
  ) { }
}
```

And the error message is:

```
Error: extraneous input ';' expecting {',', ')'} (7:10)
```

Which I think is good enough. If you didn't get a message like this, it's probably related to the way you are using prettier (maybe your IDE is not showing prettier's errors?)
