### ISSUE TITLE
Consume solium rules

### ISSUE THREAD

**Issue by jaycenhorton** [prettier-solidity/prettier-plugin-solidity#55]
It would be fantastic if the plugin would consume the rules defined in the linter ruleset, such as 

```
{
  "extends": "solium:recommended",
  "plugins": ["security"],
  "rules": {
    "quotes": ["error", "double"],
    "indentation": ["warning", 2],
    "arg-overflow": ["warning", 3],
    "security/enforce-explicit-visibility": ["error"],
    "security/no-block-members": ["warning"],
    "security/no-inline-assembly": ["warning"]
  }
}

```

So that when printing, if it sees `arg-overflow: 3`, then it prints only 3 args per line

**Comment by fvictorio** [comment]
I'm not sure about this. It raises questions like, how you decide between what is in `.prettierrc` and what is in the configuration in Solium?

When using eslint/prettier, I use both `eslint-config-prettier` (that disables all styling eslint rules) and `eslint-plugin-prettier` (that adds a rule for reporting differences with prettier as errors). I think that approach, while somewhat cumbersome to set up, is nice in the long run.

For what it's worth, the last version of [solhint](https://github.com/protofire/solhint/) has experimental support for this plugin, if you enable the `prettier/prettier` rule. But you have to manually disable all other styling rules anyway.

@mattiaerre, what do you think?

**Comment by jaycenhorton** [comment]
Depending on the difficulty, perhaps allowing an optional rule in prettierrc such as,

`use--lint-rules: solium || solhint || null`. And default to null.  Then it should be easy to map lint rules to pretty rulesets, and use whichever is defined

**Comment by mattiaerre** [comment]
I’d not be really inclined to have interactions between prettier and solium. I’m thinking at the JavaScript ecosystem and when prettier formats the code and it is breaking an eslint rule I tend to either find a prettierrc option that forces prettier to behave according to the eslint rule or I would disable that rule in the eslintrc file. E.g. double quotes, comma dangle or arrow body functions 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jaycenhorton** [comment]
I think the route of least resistance for now then might need to just line up lint rules to match formatting rules of prettier

**Comment by jaycenhorton** [comment]
Yep! closing now
