### ISSUE TITLE
Parentheses on modifiers without arguments

### ISSUE THREAD

**Issue by frangio** [prettier-solidity/prettier-plugin-solidity#554]
I expected prettier-solidty to have an opinion about parentheses on modifiers without arguments. To my knowledge, they are generally used _without_ parentheses and so they should be omitted.

```solidity
function foo() onlyOwner public {
// versus
function foo() onlyOwner() public {
```

This is related to https://github.com/prettier-solidity/prettier-plugin-solidity/issues/165 about modifier definitions, which was closed but no decision seems to have been made although it was part of the issue:
> Since prettier is supposed to be an opinionated formatter I propose that [...] prettier-solidity should always print modifier declarations without parentheses.

I agree that prettier-solidity should be opinionated about this, both for modifier definitions and uses.

**Comment by Janther** [comment]
Addressed in our latest [release](https://github.com/prettier-solidity/prettier-plugin-solidity/releases/tag/v1.0.0-beta.16)
