### ISSUE TITLE
Indent long chains

### ISSUE THREAD

**Issue by fvictorio** [prettier-solidity/prettier-plugin-solidity#559]
This is the current format we are printing:

```solidity
  uint foo = someFunction(
    foo,
    bar,
    baz
  )
  .someOtherFunction(
    foo,
    bar,
    baz
  )
```

while prettier core does something more similar to this:

```solidity
  uint foo = someFunction(
    foo,
    bar,
    baz
  )
    .someOtherFunction(
      foo,
      bar,
      baz
    )
```

See this [discussion](https://github.com/prettier-solidity/prettier-plugin-solidity/pull/557#discussion_r670732802) for more context.

**Comment by Janther** [comment]
Also I'd like to say that currently we don't indent only when the first object of the chain splits into multiple lines. If it stays in a single line we format like this:

```Solidity
  uint foo = someFunction(foo, bar, baz)
    .someOtherFunction(
      foo,
      bar,
      baz
    )
```

I like the continuity of the chain we get when the first object splits and we end with a single line having a closing `)` or `]` and right bellow it we see the next item.

This approach although nice, adds some coupling between different nodes in a sense that a `FunctionCall` has to tell the `MemberChain` some extra info about itself.

The formatting used by Prettier allows us to be decoupled.

I personally am happy with both and already provided a PR #560 to move to the new format if that's what we want.

**Comment by mattiaerre** [comment]
I think we can close this one given that #560 has been merged, would you agree @fvictorio and @Janther ?

**Comment by Janther** [comment]
There are things that I'd like to leave open for the community to discuss.
Maybe an issue is not great and a better way would be a different platform.
@fvictorio??

**Comment by fvictorio** [comment]
I tend to err on the side of closing issues instead of keeping them open. If someone has something to say, they can open a new issue, let us know in the telegram group, or just comment here since we read comments on closed issues too.

That being said, feel free to re-open if you disagree!
