### ISSUE TITLE
Should prettier be a dependency?

### ISSUE THREAD

**Issue by fvictorio** [prettier-solidity/prettier-plugin-solidity#57]
As of now, we have `prettier` inside `dependencies`. I thought it would make more sense to have it as a peer dependency. But I checked the official plugins and two of them have it as a dependency and other as a peer dependency ([python](https://github.com/prettier/plugin-python/blob/04dc40a40501a13eaec5fcb4d5c99829a31d3ffc/package.json#L17), [php](https://github.com/prettier/plugin-php/blob/3deccf883b52e681e273e4e9c1a9af2c7d039acd/package.json#L28), [swift](https://github.com/prettier/plugin-swift/blob/bdf872659d8577d09ee49b11d7730773f2f6dbe4/package.json#L17)).

@j-f1, could you give us some advice here?

**Comment by mattiaerre** [comment]
I’d keep it as a dependency for now. But this is a very good point and plugins are one of the main uses cases for peer dependencies. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fvictorio** [comment]
Sure. Sorry, I missed your comment!
