### ISSUE TITLE
Multi-string literals formatting is still not perfect

### ISSUE THREAD

**Issue by k06a** [prettier-solidity/prettier-plugin-solidity#574]
I see some issues with multiline strings formatting when they are in argument of function call. Closely related to https://github.com/prettier-solidity/prettier-plugin-solidity/issues/391.

I would love ho write:
```solidity
contract Foo
    bytes32 public constant PERMIT_TYPEHASH = keccak256(
        "Permit("
            "address owner,"
            "address spender,"
            "uint256 value,"
            "uint256 nonce,"
            "uint256 deadline"
        ")"
    );
}
```

Or at least:
```solidity
contract Foo
    bytes32 public constant PERMIT_TYPEHASH = keccak256(
        "Permit("
        "address owner,"
        "address spender,"
        "uint256 value,"
        "uint256 nonce,"
        "uint256 deadline"
        ")"
    );
}
```

But I was only able to have:
```solidity
contract Foo {
    bytes32 public constant _PERMIT_TYPEHASH =
        keccak256(
            "Permit("
            "address owner,"
            "address spender,"
            "uint256 value,"
            "uint256 nonce,"
            "uint256 deadline"
            ")"
        );
}
```

And somehow this short code:
```solidity
contract Foo {
    bytes32 public constant BALLOT_TYPEHASH =
        keccak256(
            "Ballot("
            "uint256 proposalId,"
            "uint8 support"
            ")"
        );
}
```

Was auto-formatted into this:
```solidity
contract Foo {
    bytes32 public constant BALLOT_TYPEHASH = keccak256("Ballot(" "uint256 proposalId," "uint8 support" ")");
}
```

**Comment by fvictorio** [comment]
> And somehow this short code:
> Was auto-formatted into this:

That's just the way this works for "lists of things" stuff. It looks weird in this case because of the particular content of this string, but I don't think there's something we can do (it would be crazy to do something different based on the "semantic" content of the string).

I think this is one case where adding a `// prettier-ignore` makes sense:

```solidity
contract Foo {
    // prettier-ignore
    bytes32  public constant PERMIT_TYPEHASH = keccak256(
        "Permit("
            "address owner,"
            "address spender,"
            "uint256 value,"
            "uint256 nonce,"
            "uint256 deadline"
        ")"
    );
}
```

That will ignore the whole next node, which in this case is the whole variable declaration (notice that I added an extra space after `bytes32` to illustrate this). You can do a narrower ignore like this:

```solidity
contract Foo {
    bytes32 public constant PERMIT_TYPEHASH =
        // prettier-ignore
        keccak256(
          "Permit("
              "address owner,"
              "address spender,"
              "uint256 value,"
              "uint256 nonce,"
              "uint256 deadline"
          ")"
      );
}
```

I'm going to close this because I believe there's nothing we can do, but ideas are welcome!

**Comment by k06a** [comment]
@fvictorio do you think it makes any sense to have multi-string literal in the same row? IMHO this multi-string collateral is only used for multi-row statements:

**Comment by fvictorio** [comment]
> IMHO this multi-string collateral is only used for multi-row statements.

That's a fair point, @Janther wdyt?

**Comment by Janther** [comment]
I agree, each string in its own line
