### ISSUE TITLE
feature request: solpp support

### ISSUE THREAD

**Issue by cruzdanilo** [prettier-solidity/prettier-plugin-solidity#614]
`solpp` is the most used solidity preprocessor

reference:
* https://github.com/merklejerk/solpp
* https://www.npmjs.com/package/@nomiclabs/hardhat-solpp

**Comment by Janther** [comment]
Hi @cruzdanilo,

I had a quick look at the references and to me it might look like `solpp` is the one that should run prettier as the last step of running the preprocessing.

This project is just a formatter.
Mixing in a preprocessor that not everyone will use will expand the scope of this project.

What do you think @fvictorio ?

**Comment by fvictorio** [comment]
I interpreted the request as prettier-solidity also formatting solpp comments, but maybe that's not what @cruzdanilo had in mind?

**Comment by cruzdanilo** [comment]
@fvictorio i want to be able to format solidity on vscode while editing. when i have solpp macros or expansions, i just can't format solidity code.

**Comment by Janther** [comment]
Could you share a bit more of what you want?

Explaining what you expect as input and output?
