### ISSUE TITLE
divide genericPrint into components

### ISSUE THREAD

**Issue by mattiaerre** [prettier-solidity/prettier-plugin-solidity#63]
# Description

as per now the lenght of the `printer.js` file is almost 500 lines of code; I'd love to refactor the `genericPrint` function so that we can incrementally add and replace inner "printers" w/o modifying too much the very same file; an option that I have in mind is the following:

```javascript
    // omissis
    default: {
      try {
        return [require('./node-types/for-statement')]
          .find(element => element.name === node.type)
          .print(node, path, print);
      } catch (error) {
        throw new Error(`Unknown type: ${JSON.stringify(node.type)}`);
      }
    }
    // omissis
```

where every module inside the `node-type` folder, exports an object w/ a `name` property and a `print` method; e.g.:

```javascript
/* eslint-disable implicit-arrow-linebreak */
const {
  doc: {
    builders: { concat }
  }
} = require('prettier');

const ForStatement = {
  name: 'ForStatement',
  print: (node, path, print) =>
    concat([
      'for (',
      node.initExpression ? path.call(print, 'initExpression') : '',
      '; ',
      node.conditionExpression ? path.call(print, 'conditionExpression') : '',
      '; ',
      path.call(print, 'loopExpression'),
      ') ',
      path.call(print, 'body')
    ])
};

module.exports = ForStatement;
```

what do you think?

**Comment by j-f1** [comment]
That’s a cool idea. Prettier core currently just as a 6000+ line single-file printer, but it would be cool if there was just a `nodes` directory and inside was just the name of each supported node. In cases where multiple nodes are printed in the same way, they could just re-export the master node type.

**Comment by mattiaerre** [comment]
It should be much easier to manage a structure like this for sure; I've got [this other project](https://github.com/mattiaerre/dir-to-object) that I'm currently using to compose GraphQL resolvers but I think it may be handy in this case as well. I think it would be even better to use a lookup instead of a `find`; I'll try to spike this idea as soon as #61 is fixed.

**Comment by mattiaerre** [comment]
what about:

```javascript
const dirToObject = require('dir-to-object');
const { join: pathJoin } = require('path');

const config = {
  canAdd: () => true,
  dirPath: pathJoin(__dirname, 'nodes')
};
const nodes = dirToObject(config);
```

and then

```javascript
    default: {
      try {
        return nodes[node.type].print(node, path, print);
      } catch (error) {
        throw new Error(`Unknown type: ${JSON.stringify(node.type)}`);
      }
    }
```

where the dir and the files are:

```bash
▁
/Users/foo/projects/prettier-plugin-solidity/src/nodes
└── ForStatement.js

file: 1
```

**Comment by fvictorio** [comment]
This is really cool!

I would only nitpick on how `dir-to-object` works, unless you are using it in other projects: it seems to me that doing `dirToObject(path, options)` would be a nicer API. Of course this is just bikeshedding, I like the main idea a lot.

**Comment by mattiaerre** [comment]
thanks @fvictorio I like that idea, I am the only one using that module so we can totally change it if we like (and happy to accept a PR for sure); I've also created a new PR for this project #66 what do you guys think?

// cc @j-f1 @federicobond

**Comment by Janther** [comment]
I went ahead and separated every rule into their own file.
I saw the previous PR #66 way too late.
Please have a look at #121.
There is only code splitting, same logic with small syntax changes suggested by [Prettier](https://prettier.io). Most of these where because a lot of indentation was taken away so some lines could be refactored.

**Comment by mattiaerre** [comment]
wow thanks so much @Janther for your PR, that is huge. I was wondering if you can take advantage of #66 in order to remove the explicit construction of the "Rules" object; what do you think?

**Comment by Janther** [comment]
@mattiaerre I just merged the branch of #66 and made the necessary changes in my files for it to work.
I updated the snapshot of the array so it includes the whole thing now and since the function signature is now like this `print({ node, options, path, print })`, I was able to remove all of the unused variable declarations that I had because of my old signature `nodeType(node, path, options, print)`.

**Comment by mattiaerre** [comment]
fantastic! thanks so much for that @Janther

**Comment by mattiaerre** [comment]
also @Janther please have a look at the other outstanding issues if you like 😊

**Comment by Janther** [comment]
I am 😉.

**Comment by mattiaerre** [comment]
finally closing this issue; YAY!
