### ISSUE TITLE
about space line between functions

### ISSUE THREAD

**Issue by gzliudan** [prettier-solidity/prettier-plugin-solidity#631]
Is there a rule to set space lines between functions? Sometimes no space line should be inserted between functions. Sometimes we want insert 2 space lines between functions.

```solidity
    function getVar() external view returns (uint256);
    function setVar(uint256 var) external;
```

becomes

```solidity
    function getVar() external view returns (uint256);

    function setVar(uint256 var) external;
```

**Comment by Janther** [comment]
Actually what we could do is not force the extra line *only* between abstract functions.

**Comment by mattiaerre** [comment]
Why do you think we should treat abstract functions differently? I think we should add an extra line to any functions. Do you have any recommendations from the solidity style guide? the rule you are suggesting would be a param in the prettier config or enforced at the plugin level? // cc @fvictorio @Janther

**Comment by Janther** [comment]
Because other functions have a body and abstract functions are a one liner signature of a function.

**Comment by mattiaerre** [comment]
devs can still insert lines in between and that will not be removed by prettier correct? I don't think this behavior should be enforced by the plugin my 2c

**Comment by mattiaerre** [comment]
@Janther thanks for helping me to understand the issue here and what @gzliudan is looking for, I agree w/ your initial comment then: `not force the extra line only between abstract functions.` I ➕ 1 to that

**Comment by Janther** [comment]
The latest release doesn't force line breaks between abstract functions
