### ISSUE TITLE
Format on save changes safemath types.

### ISSUE THREAD

**Issue by Neuroforge** [prettier-solidity/prettier-plugin-solidity#639]
I am using vs code solidity extension that uses prettier-plugin-solidity.

When i save, it turns the first SafeMath import from uint to uint256. What config do i need to change?

```
pragma solidity >=0.4.22 <0.9.0;

import "@openzeppelin/contracts/utils/math/SafeMath.sol";

contract MyContract {
  using SafeMath for uint;
  using SafeMath for uint256;
}
```

This is what i get when i press save. 

```
pragma solidity >=0.4.22 <0.9.0;

import "@openzeppelin/contracts/utils/math/SafeMath.sol";

contract MyContract {
  using SafeMath for uint256;   <===== THIS LINE KEEPS CHANGING
  using SafeMath for uint256;
}
```

Thanks

**Comment by fvictorio** [comment]
Hi @Neuroforge, you should set something like this:

```
{
  "overrides": [
    {
      "files": "*.sol",
      "options": {
        "explicitTypes": "preserve"
      }
    }
  ]
}
```

The possible values are `always` (which is the default, and converts `uint` to `uint256`), `never` (which converts `uint256` to `uint`) and `preserve` (which doesn't do anything).

**Comment by fvictorio** [comment]
Btw, we'll remove this option in v1.0.0 and we'll always preserve the existing types format.
