### ISSUE TITLE
Bug: extra space after list item 

### ISSUE THREAD

**Issue by sambacha** [prettier-solidity/prettier-plugin-solidity#653]
There is a prettier bug where they add extra space after a list item

this may occur when using embedded language and having a comment specified with markdown 

```typescript
const fixTabIdent = (text: string): string => {
  return text.replace(/^([ ]*)[-*][ ]+/gm, "$1- ");
};
```

see https://github.com/prettier/prettier/issues/5019

yes this is an extreme edge case

**Comment by fvictorio** [comment]
@sambacha can you give us an example of a solidity snippet that triggers this?

**Comment by Janther** [comment]
This doesn't seem to apply to our plugin. Will close. Feel free to reopen if a case is found.
