### ISSUE TITLE
Inability to format with arguments of type function

### ISSUE THREAD

**Issue by ghost** [prettier-solidity/prettier-plugin-solidity#677]
## Issue

The formatter is unable to handle files which contain code such as the following:

```solidity
function larp(function () external returns(address) f, address returned1) internal {
    vm.mockCall(
        f.address,
        abi.encodeWithSelector(f.selector),
        abi.encode(returned1)
    );
}
```

This is due to the code containing the above `function () external returns (address)` argument type.

This code compiles.

Here is an error example:

```bash
$ prettier --write 'src/**/*.sol'
src/chain.sol 72ms
src/coins.sol 7ms
src/convert.sol 22ms
src/errors.sol 37ms
src/larping.sol
[error] src/larping.sol: RangeError: index parameter must be between >= 0 and <= number of children
```

This is the file in question:

https://github.com/OlympusDAO/test-utils/blob/master/src/larping.sol

**Comment by mattiaerre** [comment]
thanks for reporting this issue @PARABRAHMAN0
