### ISSUE TITLE
Not adding semi-colons

### ISSUE THREAD

**Issue by Remscar** [prettier-solidity/prettier-plugin-solidity#681]
Given the solidity code:

```
event NetworkPurchased(uint256 networkDomainId, address owner)
event SubdomainPricingSet(uint256 domainId, PricingData pricing);
```

I would expect:

```
event NetworkPurchased(uint256 networkDomainId, address owner);
event SubdomainPricingSet(uint256 domainId, PricingData pricing);
```

But instead nothing happens and an error occurs:

```
contracts\controllers\DomainPurchaser.sol
[error] contracts\controllers\DomainPurchaser.sol: Error: mismatched input 'event' expecting {';', 'anonymous'} (68:2)
[error]     at Object.parse (G:\zer0\zns\node_modules\prettier-plugin-solidity\node_modules\@solidity-parser\parser\dist\index.cjs.js:36885:11)
[error]     at Object.parse (G:\zer0\zns\node_modules\prettier-plugin-solidity\src\parser.js:18:25)
[error]     at Object.parse (G:\zer0\zns\node_modules\prettier\index.js:7361:23)
[error]     at coreFormat (G:\zer0\zns\node_modules\prettier\index.js:8672:18)
[error]     at formatWithCursor2 (G:\zer0\zns\node_modules\prettier\index.js:8864:18)
[error]     at Object.formatWithCursor (G:\zer0\zns\node_modules\prettier\index.js:39174:12)
[error]     at format (G:\zer0\zns\node_modules\prettier\cli.js:12043:24)
[error]     at formatFiles2 (G:\zer0\zns\node_modules\prettier\cli.js:12122:20)
[error]     at async main (G:\zer0\zns\node_modules\prettier\cli.js:12327:5)
[error]     at async Object.run (G:\zer0\zns\node_modules\prettier\cli.js:12274:5)
```

**Comment by Remscar** [comment]
Same happens with code like this:
```
  // The token used to mint subdomains
  IERC20Upgradeable public paymentToken
  // Reference to the zNS Hub
  IZNSHub public zNSHub;
 ```

**Comment by fvictorio** [comment]
This is something that `prettier-solidity` cannot do. In Solidity, unlike javascript, a missing semicolon results in a parsing error. This means that the parsing stage fails before the formatting begins, so there's not much we can do. (It's technically possible to do this with a more error-tolerant parser and much more code in prettier-solidity, but both of those things are unlikely to be possible soon).

For a more specific example: supporting this would be like prettier being able to realize that a javascript file with just:

```
function () {
```

is missing the closing brace, and adding it automatically. Again: technically possible, but it's hard and it implies guesswork in the general case.

Closing this for now. Happy to explain this further if this explanation (written in a rush) is not clear enough :sweat_smile:
