### ISSUE TITLE
Formatting breaks code and it no longer compiles

### ISSUE THREAD

**Issue by Arvolear** [prettier-solidity/prettier-plugin-solidity#692]
Tested on the latest `1.0.0-beta.19` version.

The specific code snippet that the linter breaks (Test.sol file):

```
abstract contract Test {
    modifier test() virtual;
}
```

The former file compiles with no problems. Then I run the linter with the command `prettier --write Test.sol`. 

The resulting code is:

```
abstract contract Test {
    modifier test() virtual
}
```

Note that the `;` is missing.

**Comment by Janther** [comment]
@Arvolear This change is waiting for a review and will be fixed in the next version.

In the meantime consider using an empty block for the virtual function.

```Solidity
abstract contract Test {
    modifier test() virtual {_;}
}
```
