### ISSUE TITLE
the more the merrier

### ISSUE THREAD

**Issue by mattiaerre** [prettier-solidity/prettier-plugin-solidity#7]
I'll be moving this repo to the [prettier-plugin](https://github.com/prettier-solidity) organization that I've just created in GitHub as @federicobond suggested. he wrote the parser used in this plugin as well as started working on the `print` function he shares in this [Gist](https://gist.github.com/federicobond/3f7e225c5723649b2ff7de4e5156e89e). I'll send an invite also to @j-f1 as he is tremendously helping me to properly shape this prettier plugin.

**Comment by mattiaerre** [comment]
👋

**Comment by federicobond** [comment]
This week has been rough. I promise I will get back to it soon.
