### ISSUE TITLE
Symbolic imports not properly formatted

### ISSUE THREAD

**Issue by paulrberg** [prettier-solidity/prettier-plugin-solidity#702]
I have the following rule in my prettier config:

```yml
printWidth: 120
```

But it is not respected when formatting symbolic imports. Given this code:

```solidity
import { 
    checkSameSign1,
    checkSameSign2,
    checkSameSign3,
    checkSameSign4,
    checkSameSign5,
    checkSameSign6,
    checkSameSign7
} from "../src/CheckSameSign.sol";
```

Prettier will format it like this:

```solidity
import { checkSameSign1, checkSameSign2, checkSameSign3, checkSameSign4, checkSameSign5, checkSameSign6, checkSameSign7 } from "../src/CheckSameSign.sol";
```

Which will make it go above the 120 print width.

This is with prettier v2.7.1 and prettier-plugin-solidity v1.0.0-dev.22.

**Comment by Janther** [comment]
Hi,

Could you try to set the [`compiler`](https://github.com/prettier-solidity/prettier-plugin-solidity#compiler-experimental) option in the configuration file.

```JSON
{
  "compiler": "0.8.15",
  "printWidth": 120
}
```

In older versions, the compiler would not work if the import statement was split into multiple lines.

**Comment by paulrberg** [comment]
Perfect! Adding the `compiler` option made it works. Thanks Klaus.
