### ISSUE TITLE
about exponentiation

### ISSUE THREAD

**Issue by emretepedev** [prettier-solidity/prettier-plugin-solidity#704]
I want to format exponentiation symbols like in JavaScript. Also, OpenZeppelin uses it like this.

Expected Behaviour
```solidity
function foo(int x) public returns (int) {
  return x ** x;
}
```

Actual Behaviour
```solidity
function foo(int x) public returns (int) {
  return x**x;
}
```

Maybe it should be changed in the config?

**Comment by Janther** [comment]
Hi,

We decided on #174 to not to use an option for this.

We try to use as few options as possible as this is easier for maintenance.

The only use of exponentiation I could find in the OpenZeppelin contracts was [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/6ab8d6a67e3281ab062bdbe4df32b95c6409ee6d/contracts/token/ERC20/extensions/ERC4626.sol#L156-L167).

**Comment by fvictorio** [comment]
Uhm, the fact that prettier formats it that way in javascript makes me think we might want to reconsider this. On the other hand, this plugin is already used by a lot of projects, and forcing a re-format without a good reason might not be a great idea.

I say we keep this issue open for now just in case. Thanks for the data point @emretepedev.

**Comment by sambacha** [comment]
fwiw the solidity style guide only makes a distinction when used to denote precedence.

**Comment by emretepedev** [comment]
> Hi,
> 
> We decided on #174 to not to use an option for this.
> 
> We try to use as few options as possible as this is easier for maintenance.
> 
> The only use of exponentiation I could find in the OpenZeppelin contracts was [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/6ab8d6a67e3281ab062bdbe4df32b95c6409ee6d/contracts/token/ERC20/extensions/ERC4626.sol#L156-L167).

I saw in OpenZeppelin's Contracts Wizard, not in contract. [Open in Remix](https://remix.ethereum.org/?code=Ly8gU1BEWC1MaWNlbnNlLUlkZW50aWZpZXI6IE1JVApwcmFnbWEgc29saWRpdHkgXjAuOC40OwoKaW1wb3J0ICJAb3BlbnplcHBlbGluL2NvbnRyYWN0c0A0LjcuMC90b2tlbi9FUkMyMC9FUkMyMC5zb2wiOwoKY29udHJhY3QgTXlUb2tlbiBpcyBFUkMyMCB7CiAgICBjb25zdHJ1Y3RvcigpIEVSQzIwKCJNeVRva2VuIiwgIk1USyIpIHsKICAgICAgICBfbWludChtc2cuc2VuZGVyLCAyICogMTAgKiogZGVjaW1hbHMoKSk7CiAgICB9Cn0K) (copied from the [wizard](https://docs.openzeppelin.com/contracts/4.x/wizard)).

**Comment by fvictorio** [comment]
Closing this, the exponentiation operator is now surrounded with spaces.
