### ISSUE TITLE
Support for GitPOAPs

### ISSUE THREAD

**Issue by zemse** [prettier-solidity/prettier-plugin-solidity#713]
TLDR, these are poaps / nfts which are minted to any contributors, year-wise. 

More info about them: https://www.gitpoap.io

These NFTs are not typical ones that people buy or sell. But I guess it's really great way to showcase one's open-source portfolio. And also people who are interested in building their portfolio, the support for gitpoaps would attract contributors to attempt some issues, thereby improving the tool as well as the space in general.

**Comment by fvictorio** [comment]
I've already submitted this repo to GitPoap! I haven't heard back from them yet though. Do you know if there's someone we could tag on this issue about that?

**Comment by colfax23** [comment]
Awesome, we're ready to get started on onboarding this - @fvictorio can you shoot me a message on discord so I can spin up a chat with our onboarding team?  I'm colfax | GitPOAP#1983

**Comment by fvictorio** [comment]
Thanks again @zemse for raising this. We are now [included](https://www.gitpoap.io/gp/479) in GitPOAP!

There are some extra things to do, but I listed them in #761.
