### ISSUE TITLE
Invalid Telegram Invite Link

### ISSUE THREAD

**Issue by donBarbos** [prettier-solidity/prettier-plugin-solidity#716]
1. Banner have [invalid link](https://t.me/joinchat/Je2WJFCfKJ_mht1XdhBh6w) in `README.md`: 
`
[![Telegram](/assets/telegram-badge.svg)](https://t.me/joinchat/Je2WJFCfKJ_mht1XdhBh6w)
`
2. This oversight is also seen in the repository description on Github:
![Alt text](https://user-images.githubusercontent.com/47272787/185150569-f2e3aa6d-68a0-4837-9474-fe3305a121a2.png)

**Comment by fvictorio** [comment]
@donBarbos Thanks for letting us know about this!
