### ISSUE TITLE
code productivity slower after using the code formatter

### ISSUE THREAD

**Issue by henry-hz** [prettier-solidity/prettier-plugin-solidity#740]
I am trying to use the code formatter, but notice that it's much more difficult to read at one glance what variables are public, and a lot of 'white noise' is added when formatting. The first example is with the automatic format, and the second one is how I am used to format....  Is it possible to tune the code format to find symetry and organization ?

```
    // --- State ---
    IPool public pool; // Insurance pool
    IOracle public oracle; // Oracle interface
    IVault public vault; // Makers/Traders position NFT accounts
    IAccount public account; // User global account
    Queue.Data opens; // Trader open orders queue
    Queue.Data closes; // Trader close orders queue
    uint256 order_idx;
    uint256 match_idx;


    // --- State ---
    IPool    public pool;        // Insurance pool
    IOracle  public oracle;      // Oracle interface
    IVault   public vault;       // Makers/Traders position NFT accounts
    IAccount public account;     // User global account
    Queue.Data opens;            // Trader open orders queue
    Queue.Data closes;           // Trader close orders queue
    uint256 order_idx;
    uint256 match_idx;
```

**Comment by henry-hz** [comment]
pls, try to pass the formatter [here](https://github.com/makerdao/dss/blob/master/src/vat.sol) and compare the difference

**Comment by fvictorio** [comment]
Hey @henry-hz, I understand how someone could want this, but we rely heavily on prettier's core formatting. This kind of issue has been discussed on their issue tracker several times, and they've decided not to do it. See for example [this comment](https://github.com/prettier/prettier/issues/188#issuecomment-272627905) (which is about assignments, not comments, but illustrates the point).

**Comment by henry-hz** [comment]
Oh, I see. I agree that this style can fail some times, but for those who use large variables names anyway it's irrelevant, so the style could be applied only if some pre-conditions are met.  Anyway, I see that it was declined and understand the decision. Thanks for the follow up.

**Comment by mattiaerre** [comment]
Thanks, @fvictorio and @henry-hz. I'll go ahead and close this issue if there is no objection; thanks
