### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by frangio** [prettier-solidity/prettier-plugin-solidity#779]
https://github.com/prettier-solidity/prettier-plugin-solidity/blob/f927935dc8c0ce4a0da06b5a7df6063fe81ba9bc/package.json#L110
https://github.com/prettier-solidity/prettier-plugin-solidity/blob/f927935dc8c0ce4a0da06b5a7df6063fe81ba9bc/package.json#L106-L107

Couldn't find these referenced in the code.

**Comment by frangio** [comment]
Note also referenced here:

 https://github.com/prettier-solidity/prettier-plugin-solidity/blob/f927935dc8c0ce4a0da06b5a7df6063fe81ba9bc/.github/dependabot.yml#L15-L23

**Comment by Janther** [comment]
Thank you @frangio didn't notice when I cleaned up the codebase for `1.1.0`

**Comment by Janther** [comment]
@frangio we just published `v1.1.1` with mostly internal changes but this one seemed important.

**Comment by frangio** [comment]
Nice! Thanks for the notice.
