### ISSUE TITLE
solidity 0.5: breaking change

### ISSUE THREAD

**Issue by mattiaerre** [prettier-solidity/prettier-plugin-solidity#80]
as per @maxsam4 comment on Gitter:

`The JSON AST field isConstructor of the FunctionDefinition node was replaced by a field called kind which can have the value "constructor", "fallback" or "function".` this is also a breaking change.

**Comment by fvictorio** [comment]
I'm not sure I understand this issue. Do we have an example of code that makes prettier fail?

**Comment by mattiaerre** [comment]
no longer an issue; closing it

// cc @maxsam4
