### ISSUE TITLE
Add support for named parameters in mappings

### ISSUE THREAD

**Issue by fvictorio** [prettier-solidity/prettier-plugin-solidity#800]
Solc 0.8.18 was just released and adds support for named parameters in mappings:

```solidity
mapping(uint x => uint) m1;
mapping(uint => uint y) m2;
mapping(uint x => uint y) m3;
```

I already added support for it in the parser.

**Comment by PaulRBerg** [comment]
Came here to say this! Getting this error at the moment:

> Error: extraneous input 'asset' expecting '=>'
