### ISSUE TITLE
Solidity Style Guide

### ISSUE THREAD

**Issue by mattiaerre** [prettier-solidity/prettier-plugin-solidity#82]
should this plugin implement the "official" Solidity Style Guide?

https://solidity.readthedocs.io/en/v0.5.2/style-guide.html

**Comment by mattiaerre** [comment]
// cc @fvictorio @j-f1 @federicobond

**Comment by maxsam4** [comment]
I think it should by default. Setting tab space to 4 pretty much does it anyway.

**Comment by fvictorio** [comment]
I think it could eventually be used as a source for some decisions, but I wouldn't take it as hard law. In my experience, most solidity code doesn't follow it (at least the 4 spaces indentation).

Anyway, there aren't many rules related to styling there. Things like the order of functions and naming conventions should be enforced by a linter. And, as @maxsam4 said, setting the indentation to 4 spaces should be enough. I _wouldn't_ make that the default, though, but that's just my opinion.

**Comment by mattiaerre** [comment]
closing it for now
