### ISSUE TITLE
Problem with formatting when comment before contract

### ISSUE THREAD

**Issue by pizza-777** [prettier-solidity/prettier-plugin-solidity#843]
Works good:
```
pragma solidity 0.8.0;

contract Name {
	
}
```
Doesn't work:
```
pragma solidity 0.8.0;

//about the contract
contract Name {
	
}
```

How to reproduce:
1. clone this repo and npm i
2. Go to repo and run:  `npx prettier test.sol --plugin . `

**Comment by Janther** [comment]
can't replicate this and we do have tests with this scenario. can you be more specific with the error message you get?

**Comment by pizza-777** [comment]
I've got no errors in console. But there different results of formatting. 

In case without comment:
```
pragma solidity 0.8.0;

contract Name {}
```

In case with comment:
```
pragma solidity 0.8.0;

//about the contract
contract Name {
	
}
```

**Comment by Janther** [comment]
aaah I see. ok found the issue. will be posting a fix soon. thank you.
