### ISSUE TITLE
Names in mappings (Solidity 0.8.18) gives an error Error: extraneous input 'loanAddress' expecting '=>'

### ISSUE THREAD

**Issue by banshee** [prettier-solidity/prettier-plugin-solidity#854]
When we try to use names in mappings (added in Solidity 0.8.18) like this:

    mapping(address loanAddress => bool isvalid) public loanCreated;

We get an error: ```Error: extraneous input 'loanAddress' expecting '=>'```

Using these versions:

```
+    "prettier": "^2.8.8",
+    "prettier-plugin-solidity": "^1.1.3",
```

**Comment by JamesWarbler** [comment]
Tried it on this sample file:

```
pragma solidity 0.8.18;

contract Fnord {
    mapping(uint32 x => bool yesno) public something;
}
```

**Comment by banshee** [comment]
I believe this was pilot error and I was still using an old version.  Closing, sorry about that.
