### ISSUE TITLE
Unnecessary grouping of operands

### ISSUE THREAD

**Issue by LilaRest** [prettier-solidity/prettier-plugin-solidity#870]
Hi! Here is another issue :)

I've noticed that in expressions, if there are consecutive operations with the same order of precedence, this plugin groups the two first operands.
For example:
```solidity
rewards = depositedAmount * ud3ToDecimals(growthUD3) / toDecimals(100);
```
became
```solidity
rewards = (depositedAmount * ud3ToDecimals(growthUD3)) / toDecimals(100);
```

I guess that it's because it makes order of precedence more explicit, but it also makes expressions heavier. I've sometimes chosen to break expression in multiple lines because of that, which would have been totally readable on a single line without the extra parenthesis.

And this became even more confusing when as in the above example, the grouped operands contain function calls which themselves contain parenthesis.

I think most Solidity developers that work on production projects are at least familiar with the basics of Algebra, so IMO this rule will most of the time unnecessarily create heavier code.

I'd be interested to hear your opinion on the subject.

**Comment by fvictorio** [comment]
Agree! Let's see what prettier core does with js code and try to mimic that

**Comment by LilaRest** [comment]
Glad it makes sense for you too. But oops, I just tested and it seems PrettierJS also behaves the same way:
```ts
const d = a * b / c;
```
will become
```ts
const d = (a * b) / c;
```
after formatting.

So I'll close the issue for now, feel free to re-open if needed.
