### ISSUE TITLE
plugin broken with 3.0.0 prettier release

### ISSUE THREAD

**Issue by dimalinux** [prettier-solidity/prettier-plugin-solidity#885]
Prettier [released v3.0.0](https://github.com/prettier/prettier/releases/tag/3.0.0) 5 days ago and it now gives the error "No parser could be inferred for file" when formatting solidity. Downgrading to `prettier` 2.8.8 fixes the issue. Does [this PR](https://github.com/prettier-solidity/prettier-plugin-solidity/pull/848) fix the issue? If yes, any chance of a new release with it soon? Thanks!

**Comment by Janther** [comment]
`prettier 3.0.0` no longer loads external plugins automatically, have a look at the [release notes](https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker).

This means you have to declare it either in the command line, configuration file, or using the `plugins` option in the API. Here is the [documentation](https://prettier.io/docs/en/plugins.html#using-plugins).

No new release required.

The PR that you mentioned contains (among other things like testing and CI) the changes for the README to reflect these changes.

**Comment by dimalinux** [comment]
Thanks!  For anyone else having the same issue. If you installed prettier and prettier-plugin-solidity via npm, you can add this flag to fix the issue:
```text
--plugin="$(npm config get prefix)/lib/node_modules/prettier-plugin-solidity/src/index.js"
```

**Comment by Janther** [comment]
Hi @dimalinux 
`--plugin=prettier-plugin-solidity` should be enough, can you try?

**Comment by dimalinux** [comment]
That was the first way I tried. It couldn't find the plugin. In case it is part of the puzzle, my NPM install directory is configured like this (bash on Linux): https://github.com/sindresorhus/guides/blob/main/npm-global-without-sudo.md

`prettier` is in `${HOME}/.npm-packages/bin/prettier` and the plugin is in `${HOME}/.npm-packages/lib/node_modules/prettier-plugin-solidity/`
