### ISSUE TITLE
Add space after `mapping`

### ISSUE THREAD

**Issue by fvictorio** [prettier-solidity/prettier-plugin-solidity#89]
Similar to #87, there some examples of well-known solidity code that adds a space after the `mapping` keyword:

```
mapping (address => uint256)
```

But, unlike #87, here I've seen the two variations being used. And, speaking just for myself, I have a strong preference for the non-space form:

```
mapping(address => uint256)
```

Some numbers:

- [zeppelin-solidity](https://github.com/OpenZeppelin/openzeppelin-solidity):
  - **With space**: 9 times
  - **Without space**: 14 times
- [0x](https://github.com/0xProject/0x-monorepo):
  - **With space**: 29 times
  - **Without space**: 4 times
- [Gnosis Safe Contracts](https://github.com/gnosis/safe-contracts):
  - **With space**: 7 times
  - **Without space**: 3 times
- [Gnosis Multisig Wallet](https://github.com/gnosis/MultiSigWallet):
  - **With space**: 5 times
  - **Without space**: 2 times

There doesn't seem to be a strong preference for one or another, so it's probably up to us.

**Comment by mattiaerre** [comment]
for now, we are not adding any spaces but it shouldn't difficult to add one if we think that's better; let's leave this discussion open and see what we get.

**Comment by Janther** [comment]
According to the Style Guide, mapping declarations have no space.

https://solidity.readthedocs.io/en/v0.5.9/style-guide.html#mappings

Yes:
```Solidity
mapping(uint => uint) map;
mapping(address => bool) registeredAddresses;
mapping(uint => mapping(bool => Data[])) public data;
mapping(uint => mapping(uint => s)) data;
```
No:
```Solidity
mapping (uint => uint) map;
mapping( address => bool ) registeredAddresses;
mapping (uint => mapping (bool => Data[])) public data;
mapping(uint => mapping (uint => s)) data;
```

I propose we stick as much as we can to the style guide and follow changes of the community there.
The docs have way more people looking into them and it's more likely that people will get frustrated at this plugin if we enforce otherwise without offering a configuration option.

**Comment by fvictorio** [comment]
That makes sense. I will close this for the time being.
