### ISSUE TITLE
Donating Funds to prettier-plugin-solidity

### ISSUE THREAD

**Issue by Lfada** [prettier-solidity/prettier-plugin-solidity#979]
Hi Prettier-Plugin-Solidity maintainers. I'm Lucas, a core contributor to the Drips project (https://www.drips.network/). I help recipients of donations through their learning and onboarding process.

[OpenZeppelin](https://www.openzeppelin.com/) has been using https://github.com/prettier-solidity/prettier-plugin-solidity. It's one of their most critical dependencies!

OpenZeppelin core contributors appreciate your work and want to ensure you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/).

Who can I talk to about it?

cc: @Janther @mattiaerre @fvictorio

**Comment by Janther** [comment]
Hi @Lfada closing as this is not an issue and we'd like to continue the conversation on [telegram](https://t.me/+GAz2hZiME5syMjY5)
